namespace Windows.Forms
{
    partial class windowSettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.projectDirectoryLabel = new System.Windows.Forms.Label();
            this.projectDirectoryLayout = new System.Windows.Forms.FlowLayoutPanel();
            this.projectDirectoryPathText = new System.Windows.Forms.TextBox();
            this.projectDirectoryBrowseButton = new System.Windows.Forms.Button();
            this.tabPatientTypes = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.patientTypeRoomGroup = new System.Windows.Forms.GroupBox();
            this.PatientTypeChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeAutoGenerated = new System.Windows.Forms.GroupBox();
            this.patientTypesLayout = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeRoomList = new System.Windows.Forms.ListBox();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.cancelButton = new System.Windows.Forms.Button();
            this.saveButton = new System.Windows.Forms.Button();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeOtherChoicesGroup = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeMaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeFemaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeListAutoGeneratedText = new System.Windows.Forms.TextBox();
            this.patientTypeMaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.patientTypeFemaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.patientTypeOtherCheckList = new System.Windows.Forms.CheckedListBox();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.projectDirectoryLayout.SuspendLayout();
            this.tabPatientTypes.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.patientTypeRoomGroup.SuspendLayout();
            this.PatientTypeChoicesGroup.SuspendLayout();
            this.patientTypeAutoGenerated.SuspendLayout();
            this.patientTypesLayout.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.patientTypeOtherChoicesGroup.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.patientTypeMaleChoicesGroup.SuspendLayout();
            this.patientTypeFemaleChoicesGroup.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPatientTypes);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(2, 2);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1003, 686);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.tableLayoutPanel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage1.Size = new System.Drawing.Size(932, 616);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "General";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 422F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(928, 612);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.tableLayoutPanel2.Controls.Add(this.groupBox1, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(460, 608);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tableLayoutPanel3);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(2, 2);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox1.Size = new System.Drawing.Size(456, 556);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "HM4 Project Directories";
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLabel, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLayout, 0, 1);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(2, 15);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 4;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(452, 539);
            this.tableLayoutPanel3.TabIndex = 0;
            // 
            // projectDirectoryLabel
            // 
            this.projectDirectoryLabel.AutoSize = true;
            this.projectDirectoryLabel.Location = new System.Drawing.Point(2, 0);
            this.projectDirectoryLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.projectDirectoryLabel.Name = "projectDirectoryLabel";
            this.projectDirectoryLabel.Size = new System.Drawing.Size(173, 13);
            this.projectDirectoryLabel.TabIndex = 0;
            this.projectDirectoryLabel.Text = "Data directory (e.g, \'C:/hm4/data/\')";
            // 
            // projectDirectoryLayout
            // 
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryPathText);
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryBrowseButton);
            this.projectDirectoryLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryLayout.Location = new System.Drawing.Point(2, 18);
            this.projectDirectoryLayout.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryLayout.Name = "projectDirectoryLayout";
            this.projectDirectoryLayout.Size = new System.Drawing.Size(448, 28);
            this.projectDirectoryLayout.TabIndex = 1;
            // 
            // projectDirectoryPathText
            // 
            this.projectDirectoryPathText.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.projectDirectoryPathText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryPathText.Location = new System.Drawing.Point(2, 2);
            this.projectDirectoryPathText.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryPathText.MinimumSize = new System.Drawing.Size(2, 25);
            this.projectDirectoryPathText.Name = "projectDirectoryPathText";
            this.projectDirectoryPathText.Size = new System.Drawing.Size(209, 20);
            this.projectDirectoryPathText.TabIndex = 0;
            // 
            // projectDirectoryBrowseButton
            // 
            this.projectDirectoryBrowseButton.Location = new System.Drawing.Point(215, 2);
            this.projectDirectoryBrowseButton.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryBrowseButton.MinimumSize = new System.Drawing.Size(0, 20);
            this.projectDirectoryBrowseButton.Name = "projectDirectoryBrowseButton";
            this.projectDirectoryBrowseButton.Size = new System.Drawing.Size(56, 24);
            this.projectDirectoryBrowseButton.TabIndex = 1;
            this.projectDirectoryBrowseButton.Text = "Browse";
            this.projectDirectoryBrowseButton.UseVisualStyleBackColor = true;
            this.projectDirectoryBrowseButton.Click += new System.EventHandler(this.button1_Click);
            // 
            // tabPatientTypes
            // 
            this.tabPatientTypes.Controls.Add(this.patientTypesLayout);
            this.tabPatientTypes.Location = new System.Drawing.Point(4, 22);
            this.tabPatientTypes.Margin = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Name = "tabPatientTypes";
            this.tabPatientTypes.Padding = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Size = new System.Drawing.Size(995, 660);
            this.tabPatientTypes.TabIndex = 1;
            this.tabPatientTypes.Text = "Patient Types";
            this.tabPatientTypes.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 1;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Controls.Add(this.flowLayoutPanel1, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.tabControl1, 0, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 2;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(1007, 730);
            this.tableLayoutPanel4.TabIndex = 1;
            // 
            // tabPage3
            // 
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(932, 616);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Treatments";
            this.tabPage3.UseVisualStyleBackColor = true;
            // 
            // tabPage4
            // 
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage4.Size = new System.Drawing.Size(932, 616);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "Balancing";
            this.tabPage4.UseVisualStyleBackColor = true;
            // 
            // patientTypeRoomGroup
            // 
            this.patientTypeRoomGroup.Controls.Add(this.patientTypeRoomList);
            this.patientTypeRoomGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeRoomGroup.Name = "patientTypeRoomGroup";
            this.patientTypeRoomGroup.Size = new System.Drawing.Size(135, 650);
            this.patientTypeRoomGroup.TabIndex = 0;
            this.patientTypeRoomGroup.TabStop = false;
            this.patientTypeRoomGroup.Text = "Room List";
            // 
            // PatientTypeChoicesGroup
            // 
            this.PatientTypeChoicesGroup.Controls.Add(this.tableLayoutPanel6);
            this.PatientTypeChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PatientTypeChoicesGroup.Location = new System.Drawing.Point(144, 3);
            this.PatientTypeChoicesGroup.Name = "PatientTypeChoicesGroup";
            this.PatientTypeChoicesGroup.Size = new System.Drawing.Size(555, 650);
            this.PatientTypeChoicesGroup.TabIndex = 1;
            this.PatientTypeChoicesGroup.TabStop = false;
            this.PatientTypeChoicesGroup.Text = "Patient Types";
            // 
            // patientTypeAutoGenerated
            // 
            this.patientTypeAutoGenerated.Controls.Add(this.patientTypeListAutoGeneratedText);
            this.patientTypeAutoGenerated.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeAutoGenerated.Location = new System.Drawing.Point(705, 3);
            this.patientTypeAutoGenerated.Name = "patientTypeAutoGenerated";
            this.patientTypeAutoGenerated.Size = new System.Drawing.Size(283, 650);
            this.patientTypeAutoGenerated.TabIndex = 2;
            this.patientTypeAutoGenerated.TabStop = false;
            this.patientTypeAutoGenerated.Text = "Current Patient List";
            // 
            // patientTypesLayout
            // 
            this.patientTypesLayout.ColumnCount = 3;
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 56.61905F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 29.09524F));
            this.patientTypesLayout.Controls.Add(this.patientTypeAutoGenerated, 2, 0);
            this.patientTypesLayout.Controls.Add(this.patientTypeRoomGroup, 0, 0);
            this.patientTypesLayout.Controls.Add(this.PatientTypeChoicesGroup, 1, 0);
            this.patientTypesLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypesLayout.Location = new System.Drawing.Point(2, 2);
            this.patientTypesLayout.Name = "patientTypesLayout";
            this.patientTypesLayout.RowCount = 1;
            this.patientTypesLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.patientTypesLayout.Size = new System.Drawing.Size(991, 656);
            this.patientTypesLayout.TabIndex = 3;
            // 
            // patientTypeRoomList
            // 
            this.patientTypeRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomList.FormattingEnabled = true;
            this.patientTypeRoomList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeRoomList.Name = "patientTypeRoomList";
            this.patientTypeRoomList.Size = new System.Drawing.Size(129, 631);
            this.patientTypeRoomList.TabIndex = 0;
            this.patientTypeRoomList.SelectedValueChanged += new System.EventHandler(this.onPatientTypeCategorySelected);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoSize = true;
            this.flowLayoutPanel1.Controls.Add(this.cancelButton);
            this.flowLayoutPanel1.Controls.Add(this.saveButton);
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(2, 692);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.flowLayoutPanel1.MaximumSize = new System.Drawing.Size(0, 41);
            this.flowLayoutPanel1.MinimumSize = new System.Drawing.Size(0, 32);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.flowLayoutPanel1.Size = new System.Drawing.Size(1003, 36);
            this.flowLayoutPanel1.TabIndex = 2;
            // 
            // cancelButton
            // 
            this.cancelButton.Location = new System.Drawing.Point(945, 4);
            this.cancelButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.cancelButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(56, 24);
            this.cancelButton.TabIndex = 1;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.cancelButton.Click += new System.EventHandler(this.canelButton_Click);
            // 
            // saveButton
            // 
            this.saveButton.Location = new System.Drawing.Point(885, 4);
            this.saveButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.saveButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.saveButton.Name = "saveButton";
            this.saveButton.Size = new System.Drawing.Size(56, 24);
            this.saveButton.TabIndex = 0;
            this.saveButton.Text = "Save";
            this.saveButton.UseVisualStyleBackColor = true;
            this.saveButton.Click += new System.EventHandler(this.saveButton_Click);
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.ColumnCount = 1;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel6.Controls.Add(this.patientTypeOtherChoicesGroup, 0, 1);
            this.tableLayoutPanel6.Controls.Add(this.tableLayoutPanel7, 0, 0);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 2;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 67.19493F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 32.80507F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(549, 631);
            this.tableLayoutPanel6.TabIndex = 0;
            // 
            // patientTypeOtherChoicesGroup
            // 
            this.patientTypeOtherChoicesGroup.Controls.Add(this.patientTypeOtherCheckList);
            this.patientTypeOtherChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherChoicesGroup.Location = new System.Drawing.Point(3, 427);
            this.patientTypeOtherChoicesGroup.Name = "patientTypeOtherChoicesGroup";
            this.patientTypeOtherChoicesGroup.Size = new System.Drawing.Size(543, 201);
            this.patientTypeOtherChoicesGroup.TabIndex = 1;
            this.patientTypeOtherChoicesGroup.TabStop = false;
            this.patientTypeOtherChoicesGroup.Text = "Other Patients";
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.ColumnCount = 2;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.Controls.Add(this.patientTypeMaleChoicesGroup, 0, 0);
            this.tableLayoutPanel7.Controls.Add(this.patientTypeFemaleChoicesGroup, 1, 0);
            this.tableLayoutPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel7.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.RowCount = 1;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(543, 418);
            this.tableLayoutPanel7.TabIndex = 2;
            // 
            // patientTypeMaleChoicesGroup
            // 
            this.patientTypeMaleChoicesGroup.Controls.Add(this.patientTypeMaleCheckList);
            this.patientTypeMaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleChoicesGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeMaleChoicesGroup.Name = "patientTypeMaleChoicesGroup";
            this.patientTypeMaleChoicesGroup.Size = new System.Drawing.Size(265, 412);
            this.patientTypeMaleChoicesGroup.TabIndex = 0;
            this.patientTypeMaleChoicesGroup.TabStop = false;
            this.patientTypeMaleChoicesGroup.Text = "Male Patients";
            // 
            // patientTypeFemaleChoicesGroup
            // 
            this.patientTypeFemaleChoicesGroup.Controls.Add(this.patientTypeFemaleCheckList);
            this.patientTypeFemaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleChoicesGroup.Location = new System.Drawing.Point(274, 3);
            this.patientTypeFemaleChoicesGroup.Name = "patientTypeFemaleChoicesGroup";
            this.patientTypeFemaleChoicesGroup.Size = new System.Drawing.Size(266, 412);
            this.patientTypeFemaleChoicesGroup.TabIndex = 1;
            this.patientTypeFemaleChoicesGroup.TabStop = false;
            this.patientTypeFemaleChoicesGroup.Text = "Female Patients";
            // 
            // patientTypeListAutoGeneratedText
            // 
            this.patientTypeListAutoGeneratedText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeListAutoGeneratedText.Location = new System.Drawing.Point(3, 16);
            this.patientTypeListAutoGeneratedText.Multiline = true;
            this.patientTypeListAutoGeneratedText.Name = "patientTypeListAutoGeneratedText";
            this.patientTypeListAutoGeneratedText.ReadOnly = true;
            this.patientTypeListAutoGeneratedText.Size = new System.Drawing.Size(277, 631);
            this.patientTypeListAutoGeneratedText.TabIndex = 0;
            // 
            // patientTypeMaleCheckList
            // 
            this.patientTypeMaleCheckList.CheckOnClick = true;
            this.patientTypeMaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleCheckList.FormattingEnabled = true;
            this.patientTypeMaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeMaleCheckList.Name = "patientTypeMaleCheckList";
            this.patientTypeMaleCheckList.Size = new System.Drawing.Size(259, 393);
            this.patientTypeMaleCheckList.Sorted = true;
            this.patientTypeMaleCheckList.TabIndex = 0;
            // 
            // patientTypeFemaleCheckList
            // 
            this.patientTypeFemaleCheckList.CheckOnClick = true;
            this.patientTypeFemaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleCheckList.FormattingEnabled = true;
            this.patientTypeFemaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeFemaleCheckList.Name = "patientTypeFemaleCheckList";
            this.patientTypeFemaleCheckList.Size = new System.Drawing.Size(260, 393);
            this.patientTypeFemaleCheckList.TabIndex = 0;
            // 
            // patientTypeOtherCheckList
            // 
            this.patientTypeOtherCheckList.CheckOnClick = true;
            this.patientTypeOtherCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherCheckList.FormattingEnabled = true;
            this.patientTypeOtherCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeOtherCheckList.MultiColumn = true;
            this.patientTypeOtherCheckList.Name = "patientTypeOtherCheckList";
            this.patientTypeOtherCheckList.Size = new System.Drawing.Size(537, 182);
            this.patientTypeOtherCheckList.TabIndex = 0;
            // 
            // windowSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1007, 730);
            this.Controls.Add(this.tableLayoutPanel4);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.MinimumSize = new System.Drawing.Size(604, 495);
            this.Name = "windowSettings";
            this.Text = "Settings";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.projectDirectoryLayout.ResumeLayout(false);
            this.projectDirectoryLayout.PerformLayout();
            this.tabPatientTypes.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.patientTypeRoomGroup.ResumeLayout(false);
            this.PatientTypeChoicesGroup.ResumeLayout(false);
            this.patientTypeAutoGenerated.ResumeLayout(false);
            this.patientTypeAutoGenerated.PerformLayout();
            this.patientTypesLayout.ResumeLayout(false);
            this.flowLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.patientTypeOtherChoicesGroup.ResumeLayout(false);
            this.tableLayoutPanel7.ResumeLayout(false);
            this.patientTypeMaleChoicesGroup.ResumeLayout(false);
            this.patientTypeFemaleChoicesGroup.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label projectDirectoryLabel;
        private System.Windows.Forms.FlowLayoutPanel projectDirectoryLayout;
        private System.Windows.Forms.TextBox projectDirectoryPathText;
        private System.Windows.Forms.Button projectDirectoryBrowseButton;
        private System.Windows.Forms.TabPage tabPatientTypes;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TableLayoutPanel patientTypesLayout;
        private System.Windows.Forms.GroupBox patientTypeAutoGenerated;
        private System.Windows.Forms.GroupBox patientTypeRoomGroup;
        private System.Windows.Forms.GroupBox PatientTypeChoicesGroup;
        private System.Windows.Forms.ListBox patientTypeRoomList;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button saveButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.GroupBox patientTypeOtherChoicesGroup;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
        private System.Windows.Forms.GroupBox patientTypeMaleChoicesGroup;
        private System.Windows.Forms.GroupBox patientTypeFemaleChoicesGroup;
        private System.Windows.Forms.TextBox patientTypeListAutoGeneratedText;
        private System.Windows.Forms.CheckedListBox patientTypeMaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeFemaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeOtherCheckList;
    }
}