namespace Windows
{
    partial class windowSettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.projectDirectoryLabel = new System.Windows.Forms.Label();
            this.projectDirectoryLayout = new System.Windows.Forms.FlowLayoutPanel();
            this.projectDirectoryPathText = new System.Windows.Forms.TextBox();
            this.projectDirectoryBrowseButton = new System.Windows.Forms.Button();
            this.tabPatientTypes = new System.Windows.Forms.TabPage();
            this.patientTypesLayout = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeAutoGenerated = new System.Windows.Forms.GroupBox();
            this.patientTypeListAutoGeneratedText = new System.Windows.Forms.TextBox();
            this.patientTypeRoomGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeRoomList = new System.Windows.Forms.ListBox();
            this.PatientTypeChoicesGroup = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeOtherChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeOtherCheckList = new System.Windows.Forms.CheckedListBox();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeMaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeMaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.patientTypeFemaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeFemaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.treatmentRoomListGroup = new System.Windows.Forms.GroupBox();
            this.treatmentRoomList = new System.Windows.Forms.ListBox();
            this.tableLayoutPanel8 = new System.Windows.Forms.TableLayoutPanel();
            this.treatmentDataGridView = new System.Windows.Forms.DataGridView();
            this.treatmentSelect = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.treatmentName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.difficultyUnlocked = new System.Windows.Forms.DataGridViewComboBoxColumn();
            this.heartsValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.weight = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.weightPercentage = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.gesture = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.alwaysLast = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.colorButton = new System.Windows.Forms.DataGridViewButtonColumn();
            this.colorValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.treatmentRowButtonAdd = new System.Windows.Forms.Button();
            this.treatmentRowButtonRemove = new System.Windows.Forms.Button();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel9 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel11 = new System.Windows.Forms.TableLayoutPanel();
            this.minutesPerLevelValue = new System.Windows.Forms.TextBox();
            this.milliSecondsPerLevelValue = new System.Windows.Forms.TextBox();
            this.timePerTreatmentValue = new System.Windows.Forms.TextBox();
            this.treatmentPerPatientValue = new System.Windows.Forms.TextBox();
            this.minutesPerLevelLabel = new System.Windows.Forms.Label();
            this.milliSecondsPerLevelLabel = new System.Windows.Forms.Label();
            this.timePerTreatmentLabel = new System.Windows.Forms.Label();
            this.treatmentPerPatientLabel = new System.Windows.Forms.Label();
            this.numberOfPatientsLabel = new System.Windows.Forms.Label();
            this.numberOfPatientsValue = new System.Windows.Forms.TextBox();
            this.timeBetweenPatientsValue = new System.Windows.Forms.TextBox();
            this.averageEntryTimePerPatientLabel = new System.Windows.Forms.Label();
            this.timeBetweenPatientsLabel = new System.Windows.Forms.Label();
            this.averageEntryTimePerPatientValue = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.balancingRoomList = new System.Windows.Forms.ListBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel10 = new System.Windows.Forms.TableLayoutPanel();
            this.difficultyModifierList = new System.Windows.Forms.ListBox();
            this.tableLayoutPanel13 = new System.Windows.Forms.TableLayoutPanel();
            this.buttonAddDiffModifier = new System.Windows.Forms.Button();
            this.buttonRemoveDiffModifier = new System.Windows.Forms.Button();
            this.diffModifierValue = new System.Windows.Forms.NumericUpDown();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel12 = new System.Windows.Forms.TableLayoutPanel();
            this.difficultyModifierTreatmentsBasedLabel = new System.Windows.Forms.Label();
            this.difficultyModifierTreatmentsBasedValue = new System.Windows.Forms.TextBox();
            this.startLevelDurationLabel = new System.Windows.Forms.Label();
            this.startLevelDurationValue = new System.Windows.Forms.TextBox();
            this.timeIncreasePerLevelLabel = new System.Windows.Forms.Label();
            this.timeIncreasePerLevelValue = new System.Windows.Forms.TextBox();
            this.initialTimePerTreatmentLabel = new System.Windows.Forms.Label();
            this.decreaseTimePerTreatmentLabel = new System.Windows.Forms.Label();
            this.decreaseTimePerTreatmentValue = new System.Windows.Forms.TextBox();
            this.initialTimePerTreatmentValue = new System.Windows.Forms.TextBox();
            this.decreaseTimeBetweenPatientsValue = new System.Windows.Forms.TextBox();
            this.initialTimeBetweenPatientsValue = new System.Windows.Forms.TextBox();
            this.decreaseTimeBetweenPatientsLabel = new System.Windows.Forms.Label();
            this.initialTimeBetweenPatientsLabel = new System.Windows.Forms.Label();
            this.checkoutPerPatientValue = new System.Windows.Forms.TextBox();
            this.treatmentMinimumTimeValue = new System.Windows.Forms.TextBox();
            this.checkoutPerPatientLabel = new System.Windows.Forms.Label();
            this.treatmentMinimumTimelabel = new System.Windows.Forms.Label();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.cancelButton = new System.Windows.Forms.Button();
            this.saveButton = new System.Windows.Forms.Button();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.projectDirectoryLayout.SuspendLayout();
            this.tabPatientTypes.SuspendLayout();
            this.patientTypesLayout.SuspendLayout();
            this.patientTypeAutoGenerated.SuspendLayout();
            this.patientTypeRoomGroup.SuspendLayout();
            this.PatientTypeChoicesGroup.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.patientTypeOtherChoicesGroup.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.patientTypeMaleChoicesGroup.SuspendLayout();
            this.patientTypeFemaleChoicesGroup.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.treatmentRoomListGroup.SuspendLayout();
            this.tableLayoutPanel8.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.treatmentDataGridView)).BeginInit();
            this.flowLayoutPanel2.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tableLayoutPanel9.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.tableLayoutPanel11.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.tableLayoutPanel10.SuspendLayout();
            this.tableLayoutPanel13.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.diffModifierValue)).BeginInit();
            this.groupBox5.SuspendLayout();
            this.tableLayoutPanel12.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPatientTypes);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(2, 2);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1003, 686);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.tableLayoutPanel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage1.Size = new System.Drawing.Size(995, 660);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "General";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 656F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(991, 656);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.tableLayoutPanel2.Controls.Add(this.groupBox1, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(491, 652);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tableLayoutPanel3);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(2, 2);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox1.Size = new System.Drawing.Size(487, 600);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "HM4 Project Directories";
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLabel, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLayout, 0, 1);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(2, 15);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 4;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(483, 583);
            this.tableLayoutPanel3.TabIndex = 0;
            // 
            // projectDirectoryLabel
            // 
            this.projectDirectoryLabel.AutoSize = true;
            this.projectDirectoryLabel.Location = new System.Drawing.Point(2, 0);
            this.projectDirectoryLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.projectDirectoryLabel.Name = "projectDirectoryLabel";
            this.projectDirectoryLabel.Size = new System.Drawing.Size(173, 13);
            this.projectDirectoryLabel.TabIndex = 0;
            this.projectDirectoryLabel.Text = "Data directory (e.g, \'C:/hm4/data/\')";
            // 
            // projectDirectoryLayout
            // 
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryPathText);
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryBrowseButton);
            this.projectDirectoryLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryLayout.Location = new System.Drawing.Point(2, 18);
            this.projectDirectoryLayout.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryLayout.Name = "projectDirectoryLayout";
            this.projectDirectoryLayout.Size = new System.Drawing.Size(479, 28);
            this.projectDirectoryLayout.TabIndex = 1;
            // 
            // projectDirectoryPathText
            // 
            this.projectDirectoryPathText.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.projectDirectoryPathText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryPathText.Location = new System.Drawing.Point(2, 2);
            this.projectDirectoryPathText.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryPathText.MinimumSize = new System.Drawing.Size(2, 25);
            this.projectDirectoryPathText.Name = "projectDirectoryPathText";
            this.projectDirectoryPathText.Size = new System.Drawing.Size(209, 20);
            this.projectDirectoryPathText.TabIndex = 0;
            // 
            // projectDirectoryBrowseButton
            // 
            this.projectDirectoryBrowseButton.Location = new System.Drawing.Point(215, 2);
            this.projectDirectoryBrowseButton.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryBrowseButton.MinimumSize = new System.Drawing.Size(0, 20);
            this.projectDirectoryBrowseButton.Name = "projectDirectoryBrowseButton";
            this.projectDirectoryBrowseButton.Size = new System.Drawing.Size(56, 24);
            this.projectDirectoryBrowseButton.TabIndex = 1;
            this.projectDirectoryBrowseButton.Text = "Browse";
            this.projectDirectoryBrowseButton.UseVisualStyleBackColor = true;
            this.projectDirectoryBrowseButton.Click += new System.EventHandler(this.button1_Click);
            // 
            // tabPatientTypes
            // 
            this.tabPatientTypes.Controls.Add(this.patientTypesLayout);
            this.tabPatientTypes.Location = new System.Drawing.Point(4, 22);
            this.tabPatientTypes.Margin = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Name = "tabPatientTypes";
            this.tabPatientTypes.Padding = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Size = new System.Drawing.Size(995, 660);
            this.tabPatientTypes.TabIndex = 1;
            this.tabPatientTypes.Text = "Patient Types";
            this.tabPatientTypes.UseVisualStyleBackColor = true;
            // 
            // patientTypesLayout
            // 
            this.patientTypesLayout.ColumnCount = 3;
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 66.05556F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.94445F));
            this.patientTypesLayout.Controls.Add(this.patientTypeAutoGenerated, 2, 0);
            this.patientTypesLayout.Controls.Add(this.patientTypeRoomGroup, 0, 0);
            this.patientTypesLayout.Controls.Add(this.PatientTypeChoicesGroup, 1, 0);
            this.patientTypesLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypesLayout.Location = new System.Drawing.Point(2, 2);
            this.patientTypesLayout.Name = "patientTypesLayout";
            this.patientTypesLayout.RowCount = 1;
            this.patientTypesLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.patientTypesLayout.Size = new System.Drawing.Size(991, 656);
            this.patientTypesLayout.TabIndex = 3;
            // 
            // patientTypeAutoGenerated
            // 
            this.patientTypeAutoGenerated.Controls.Add(this.patientTypeListAutoGeneratedText);
            this.patientTypeAutoGenerated.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeAutoGenerated.Location = new System.Drawing.Point(708, 3);
            this.patientTypeAutoGenerated.Name = "patientTypeAutoGenerated";
            this.patientTypeAutoGenerated.Size = new System.Drawing.Size(280, 650);
            this.patientTypeAutoGenerated.TabIndex = 2;
            this.patientTypeAutoGenerated.TabStop = false;
            this.patientTypeAutoGenerated.Text = "Current Patient List";
            // 
            // patientTypeListAutoGeneratedText
            // 
            this.patientTypeListAutoGeneratedText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeListAutoGeneratedText.Location = new System.Drawing.Point(3, 16);
            this.patientTypeListAutoGeneratedText.Multiline = true;
            this.patientTypeListAutoGeneratedText.Name = "patientTypeListAutoGeneratedText";
            this.patientTypeListAutoGeneratedText.ReadOnly = true;
            this.patientTypeListAutoGeneratedText.Size = new System.Drawing.Size(274, 631);
            this.patientTypeListAutoGeneratedText.TabIndex = 0;
            // 
            // patientTypeRoomGroup
            // 
            this.patientTypeRoomGroup.Controls.Add(this.patientTypeRoomList);
            this.patientTypeRoomGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeRoomGroup.Name = "patientTypeRoomGroup";
            this.patientTypeRoomGroup.Size = new System.Drawing.Size(144, 650);
            this.patientTypeRoomGroup.TabIndex = 0;
            this.patientTypeRoomGroup.TabStop = false;
            this.patientTypeRoomGroup.Text = "Room List";
            // 
            // patientTypeRoomList
            // 
            this.patientTypeRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomList.FormattingEnabled = true;
            this.patientTypeRoomList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeRoomList.Name = "patientTypeRoomList";
            this.patientTypeRoomList.Size = new System.Drawing.Size(138, 631);
            this.patientTypeRoomList.TabIndex = 0;
            this.patientTypeRoomList.SelectedValueChanged += new System.EventHandler(this.OnPatientTypeCategorySelected);
            // 
            // PatientTypeChoicesGroup
            // 
            this.PatientTypeChoicesGroup.Controls.Add(this.tableLayoutPanel6);
            this.PatientTypeChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PatientTypeChoicesGroup.Location = new System.Drawing.Point(153, 3);
            this.PatientTypeChoicesGroup.Name = "PatientTypeChoicesGroup";
            this.PatientTypeChoicesGroup.Size = new System.Drawing.Size(549, 650);
            this.PatientTypeChoicesGroup.TabIndex = 1;
            this.PatientTypeChoicesGroup.TabStop = false;
            this.PatientTypeChoicesGroup.Text = "Patient Types";
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.ColumnCount = 1;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel6.Controls.Add(this.patientTypeOtherChoicesGroup, 0, 1);
            this.tableLayoutPanel6.Controls.Add(this.tableLayoutPanel7, 0, 0);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 2;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 67.19493F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 32.80507F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(543, 631);
            this.tableLayoutPanel6.TabIndex = 0;
            // 
            // patientTypeOtherChoicesGroup
            // 
            this.patientTypeOtherChoicesGroup.Controls.Add(this.patientTypeOtherCheckList);
            this.patientTypeOtherChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherChoicesGroup.Location = new System.Drawing.Point(3, 427);
            this.patientTypeOtherChoicesGroup.Name = "patientTypeOtherChoicesGroup";
            this.patientTypeOtherChoicesGroup.Size = new System.Drawing.Size(537, 201);
            this.patientTypeOtherChoicesGroup.TabIndex = 1;
            this.patientTypeOtherChoicesGroup.TabStop = false;
            this.patientTypeOtherChoicesGroup.Text = "Other Patients";
            // 
            // patientTypeOtherCheckList
            // 
            this.patientTypeOtherCheckList.CheckOnClick = true;
            this.patientTypeOtherCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherCheckList.FormattingEnabled = true;
            this.patientTypeOtherCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeOtherCheckList.MultiColumn = true;
            this.patientTypeOtherCheckList.Name = "patientTypeOtherCheckList";
            this.patientTypeOtherCheckList.Size = new System.Drawing.Size(531, 182);
            this.patientTypeOtherCheckList.TabIndex = 0;
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.ColumnCount = 2;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.Controls.Add(this.patientTypeMaleChoicesGroup, 0, 0);
            this.tableLayoutPanel7.Controls.Add(this.patientTypeFemaleChoicesGroup, 1, 0);
            this.tableLayoutPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel7.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.RowCount = 1;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 418F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(537, 418);
            this.tableLayoutPanel7.TabIndex = 2;
            // 
            // patientTypeMaleChoicesGroup
            // 
            this.patientTypeMaleChoicesGroup.Controls.Add(this.patientTypeMaleCheckList);
            this.patientTypeMaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleChoicesGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeMaleChoicesGroup.Name = "patientTypeMaleChoicesGroup";
            this.patientTypeMaleChoicesGroup.Size = new System.Drawing.Size(262, 412);
            this.patientTypeMaleChoicesGroup.TabIndex = 0;
            this.patientTypeMaleChoicesGroup.TabStop = false;
            this.patientTypeMaleChoicesGroup.Text = "Male Patients";
            // 
            // patientTypeMaleCheckList
            // 
            this.patientTypeMaleCheckList.CheckOnClick = true;
            this.patientTypeMaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleCheckList.FormattingEnabled = true;
            this.patientTypeMaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeMaleCheckList.Name = "patientTypeMaleCheckList";
            this.patientTypeMaleCheckList.Size = new System.Drawing.Size(256, 393);
            this.patientTypeMaleCheckList.Sorted = true;
            this.patientTypeMaleCheckList.TabIndex = 0;
            // 
            // patientTypeFemaleChoicesGroup
            // 
            this.patientTypeFemaleChoicesGroup.Controls.Add(this.patientTypeFemaleCheckList);
            this.patientTypeFemaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleChoicesGroup.Location = new System.Drawing.Point(271, 3);
            this.patientTypeFemaleChoicesGroup.Name = "patientTypeFemaleChoicesGroup";
            this.patientTypeFemaleChoicesGroup.Size = new System.Drawing.Size(263, 412);
            this.patientTypeFemaleChoicesGroup.TabIndex = 1;
            this.patientTypeFemaleChoicesGroup.TabStop = false;
            this.patientTypeFemaleChoicesGroup.Text = "Female Patients";
            // 
            // patientTypeFemaleCheckList
            // 
            this.patientTypeFemaleCheckList.CheckOnClick = true;
            this.patientTypeFemaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleCheckList.FormattingEnabled = true;
            this.patientTypeFemaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeFemaleCheckList.Name = "patientTypeFemaleCheckList";
            this.patientTypeFemaleCheckList.Size = new System.Drawing.Size(257, 393);
            this.patientTypeFemaleCheckList.TabIndex = 0;
            // 
            // tabPage3
            // 
            this.tabPage3.Controls.Add(this.tableLayoutPanel5);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(995, 660);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Treatments";
            this.tabPage3.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Controls.Add(this.treatmentRoomListGroup, 0, 0);
            this.tableLayoutPanel5.Controls.Add(this.tableLayoutPanel8, 1, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(989, 654);
            this.tableLayoutPanel5.TabIndex = 4;
            // 
            // treatmentRoomListGroup
            // 
            this.treatmentRoomListGroup.Controls.Add(this.treatmentRoomList);
            this.treatmentRoomListGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentRoomListGroup.Location = new System.Drawing.Point(3, 3);
            this.treatmentRoomListGroup.Name = "treatmentRoomListGroup";
            this.treatmentRoomListGroup.Size = new System.Drawing.Size(144, 648);
            this.treatmentRoomListGroup.TabIndex = 0;
            this.treatmentRoomListGroup.TabStop = false;
            this.treatmentRoomListGroup.Text = "Room List";
            // 
            // treatmentRoomList
            // 
            this.treatmentRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentRoomList.FormattingEnabled = true;
            this.treatmentRoomList.Location = new System.Drawing.Point(3, 16);
            this.treatmentRoomList.Name = "treatmentRoomList";
            this.treatmentRoomList.Size = new System.Drawing.Size(138, 629);
            this.treatmentRoomList.TabIndex = 0;
            this.treatmentRoomList.Click += new System.EventHandler(this.OnTreatmentCategorySelected);
            // 
            // tableLayoutPanel8
            // 
            this.tableLayoutPanel8.ColumnCount = 1;
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel8.Controls.Add(this.treatmentDataGridView, 0, 0);
            this.tableLayoutPanel8.Controls.Add(this.flowLayoutPanel2, 0, 1);
            this.tableLayoutPanel8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel8.Location = new System.Drawing.Point(153, 3);
            this.tableLayoutPanel8.Name = "tableLayoutPanel8";
            this.tableLayoutPanel8.RowCount = 2;
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel8.Size = new System.Drawing.Size(833, 648);
            this.tableLayoutPanel8.TabIndex = 1;
            // 
            // treatmentDataGridView
            // 
            this.treatmentDataGridView.AllowUserToAddRows = false;
            this.treatmentDataGridView.AllowUserToDeleteRows = false;
            this.treatmentDataGridView.AllowUserToOrderColumns = true;
            this.treatmentDataGridView.AllowUserToResizeRows = false;
            this.treatmentDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.treatmentDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.treatmentDataGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.treatmentSelect,
            this.treatmentName,
            this.difficultyUnlocked,
            this.heartsValue,
            this.weight,
            this.weightPercentage,
            this.gesture,
            this.alwaysLast,
            this.colorButton,
            this.colorValue});
            this.treatmentDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentDataGridView.EditMode = System.Windows.Forms.DataGridViewEditMode.EditOnEnter;
            this.treatmentDataGridView.Location = new System.Drawing.Point(3, 3);
            this.treatmentDataGridView.MultiSelect = false;
            this.treatmentDataGridView.Name = "treatmentDataGridView";
            this.treatmentDataGridView.RowHeadersVisible = false;
            this.treatmentDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
            this.treatmentDataGridView.Size = new System.Drawing.Size(827, 602);
            this.treatmentDataGridView.TabIndex = 2;
            this.treatmentDataGridView.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.treatmentDataGridView_CellContentClick);
            // 
            // treatmentSelect
            // 
            this.treatmentSelect.HeaderText = "";
            this.treatmentSelect.Name = "treatmentSelect";
            this.treatmentSelect.Width = 30;
            // 
            // treatmentName
            // 
            this.treatmentName.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.treatmentName.HeaderText = "Treatment Name";
            this.treatmentName.Name = "treatmentName";
            // 
            // difficultyUnlocked
            // 
            this.difficultyUnlocked.HeaderText = "Difficulty Unlocked";
            this.difficultyUnlocked.Name = "difficultyUnlocked";
            // 
            // heartsValue
            // 
            this.heartsValue.HeaderText = "Hearts Value";
            this.heartsValue.Name = "heartsValue";
            // 
            // weight
            // 
            this.weight.HeaderText = "Weight";
            this.weight.Name = "weight";
            this.weight.Width = 50;
            // 
            // weightPercentage
            // 
            this.weightPercentage.HeaderText = "";
            this.weightPercentage.Name = "weightPercentage";
            this.weightPercentage.ReadOnly = true;
            this.weightPercentage.Width = 50;
            // 
            // gesture
            // 
            this.gesture.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.gesture.HeaderText = "Gesture";
            this.gesture.Name = "gesture";
            this.gesture.Width = 50;
            // 
            // alwaysLast
            // 
            this.alwaysLast.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.alwaysLast.HeaderText = "Always Last";
            this.alwaysLast.Name = "alwaysLast";
            this.alwaysLast.Width = 69;
            // 
            // colorButton
            // 
            this.colorButton.HeaderText = "Color";
            this.colorButton.Name = "colorButton";
            // 
            // colorValue
            // 
            this.colorValue.HeaderText = "Value";
            this.colorValue.Name = "colorValue";
            this.colorValue.ReadOnly = true;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.Controls.Add(this.treatmentRowButtonAdd);
            this.flowLayoutPanel2.Controls.Add(this.treatmentRowButtonRemove);
            this.flowLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel2.Location = new System.Drawing.Point(3, 611);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(827, 34);
            this.flowLayoutPanel2.TabIndex = 3;
            // 
            // treatmentRowButtonAdd
            // 
            this.treatmentRowButtonAdd.Location = new System.Drawing.Point(3, 3);
            this.treatmentRowButtonAdd.Name = "treatmentRowButtonAdd";
            this.treatmentRowButtonAdd.Size = new System.Drawing.Size(75, 23);
            this.treatmentRowButtonAdd.TabIndex = 0;
            this.treatmentRowButtonAdd.Text = "Add";
            this.treatmentRowButtonAdd.UseVisualStyleBackColor = true;
            this.treatmentRowButtonAdd.Click += new System.EventHandler(this.TreatmentRowButtonAdd_Click);
            // 
            // treatmentRowButtonRemove
            // 
            this.treatmentRowButtonRemove.Location = new System.Drawing.Point(84, 3);
            this.treatmentRowButtonRemove.Name = "treatmentRowButtonRemove";
            this.treatmentRowButtonRemove.Size = new System.Drawing.Size(75, 23);
            this.treatmentRowButtonRemove.TabIndex = 1;
            this.treatmentRowButtonRemove.Text = "Remove";
            this.treatmentRowButtonRemove.UseVisualStyleBackColor = true;
            this.treatmentRowButtonRemove.Click += new System.EventHandler(this.TreatmentRowButtonRemove_Click);
            // 
            // tabPage4
            // 
            this.tabPage4.Controls.Add(this.tableLayoutPanel9);
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage4.Size = new System.Drawing.Size(995, 660);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "Balancing";
            this.tabPage4.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel9
            // 
            this.tableLayoutPanel9.ColumnCount = 4;
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 250F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50.7054F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49.2946F));
            this.tableLayoutPanel9.Controls.Add(this.groupBox2, 2, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox3, 0, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox4, 1, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox5, 3, 0);
            this.tableLayoutPanel9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel9.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel9.Name = "tableLayoutPanel9";
            this.tableLayoutPanel9.RowCount = 1;
            this.tableLayoutPanel9.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel9.Size = new System.Drawing.Size(989, 654);
            this.tableLayoutPanel9.TabIndex = 4;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.tableLayoutPanel11);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox2.Location = new System.Drawing.Point(403, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(292, 648);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Calculated Values";
            // 
            // tableLayoutPanel11
            // 
            this.tableLayoutPanel11.ColumnCount = 2;
            this.tableLayoutPanel11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61.76471F));
            this.tableLayoutPanel11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38.23529F));
            this.tableLayoutPanel11.Controls.Add(this.minutesPerLevelValue, 1, 6);
            this.tableLayoutPanel11.Controls.Add(this.milliSecondsPerLevelValue, 1, 5);
            this.tableLayoutPanel11.Controls.Add(this.timePerTreatmentValue, 1, 4);
            this.tableLayoutPanel11.Controls.Add(this.treatmentPerPatientValue, 1, 3);
            this.tableLayoutPanel11.Controls.Add(this.minutesPerLevelLabel, 0, 6);
            this.tableLayoutPanel11.Controls.Add(this.milliSecondsPerLevelLabel, 0, 5);
            this.tableLayoutPanel11.Controls.Add(this.timePerTreatmentLabel, 0, 4);
            this.tableLayoutPanel11.Controls.Add(this.treatmentPerPatientLabel, 0, 3);
            this.tableLayoutPanel11.Controls.Add(this.numberOfPatientsLabel, 0, 2);
            this.tableLayoutPanel11.Controls.Add(this.numberOfPatientsValue, 1, 2);
            this.tableLayoutPanel11.Controls.Add(this.timeBetweenPatientsValue, 1, 1);
            this.tableLayoutPanel11.Controls.Add(this.averageEntryTimePerPatientLabel, 0, 0);
            this.tableLayoutPanel11.Controls.Add(this.timeBetweenPatientsLabel, 0, 1);
            this.tableLayoutPanel11.Controls.Add(this.averageEntryTimePerPatientValue, 1, 0);
            this.tableLayoutPanel11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel11.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel11.Name = "tableLayoutPanel11";
            this.tableLayoutPanel11.RowCount = 8;
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel11.Size = new System.Drawing.Size(286, 629);
            this.tableLayoutPanel11.TabIndex = 0;
            // 
            // minutesPerLevelValue
            // 
            this.minutesPerLevelValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.minutesPerLevelValue.Location = new System.Drawing.Point(179, 276);
            this.minutesPerLevelValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.minutesPerLevelValue.Name = "minutesPerLevelValue";
            this.minutesPerLevelValue.ReadOnly = true;
            this.minutesPerLevelValue.Size = new System.Drawing.Size(104, 20);
            this.minutesPerLevelValue.TabIndex = 17;
            // 
            // milliSecondsPerLevelValue
            // 
            this.milliSecondsPerLevelValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.milliSecondsPerLevelValue.Location = new System.Drawing.Point(179, 232);
            this.milliSecondsPerLevelValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.milliSecondsPerLevelValue.Name = "milliSecondsPerLevelValue";
            this.milliSecondsPerLevelValue.ReadOnly = true;
            this.milliSecondsPerLevelValue.Size = new System.Drawing.Size(104, 20);
            this.milliSecondsPerLevelValue.TabIndex = 16;
            // 
            // timePerTreatmentValue
            // 
            this.timePerTreatmentValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timePerTreatmentValue.Location = new System.Drawing.Point(179, 188);
            this.timePerTreatmentValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.timePerTreatmentValue.Name = "timePerTreatmentValue";
            this.timePerTreatmentValue.ReadOnly = true;
            this.timePerTreatmentValue.Size = new System.Drawing.Size(104, 20);
            this.timePerTreatmentValue.TabIndex = 15;
            // 
            // treatmentPerPatientValue
            // 
            this.treatmentPerPatientValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentPerPatientValue.Location = new System.Drawing.Point(179, 144);
            this.treatmentPerPatientValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.treatmentPerPatientValue.Name = "treatmentPerPatientValue";
            this.treatmentPerPatientValue.ReadOnly = true;
            this.treatmentPerPatientValue.Size = new System.Drawing.Size(104, 20);
            this.treatmentPerPatientValue.TabIndex = 14;
            // 
            // minutesPerLevelLabel
            // 
            this.minutesPerLevelLabel.AutoSize = true;
            this.minutesPerLevelLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.minutesPerLevelLabel.Location = new System.Drawing.Point(3, 264);
            this.minutesPerLevelLabel.Name = "minutesPerLevelLabel";
            this.minutesPerLevelLabel.Size = new System.Drawing.Size(170, 44);
            this.minutesPerLevelLabel.TabIndex = 13;
            this.minutesPerLevelLabel.Text = "Minutes per Level";
            this.minutesPerLevelLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // milliSecondsPerLevelLabel
            // 
            this.milliSecondsPerLevelLabel.AutoSize = true;
            this.milliSecondsPerLevelLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.milliSecondsPerLevelLabel.Location = new System.Drawing.Point(3, 220);
            this.milliSecondsPerLevelLabel.Name = "milliSecondsPerLevelLabel";
            this.milliSecondsPerLevelLabel.Size = new System.Drawing.Size(170, 44);
            this.milliSecondsPerLevelLabel.TabIndex = 11;
            this.milliSecondsPerLevelLabel.Text = "Milisecond per Level";
            this.milliSecondsPerLevelLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // timePerTreatmentLabel
            // 
            this.timePerTreatmentLabel.AutoSize = true;
            this.timePerTreatmentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timePerTreatmentLabel.Location = new System.Drawing.Point(3, 176);
            this.timePerTreatmentLabel.Name = "timePerTreatmentLabel";
            this.timePerTreatmentLabel.Size = new System.Drawing.Size(170, 44);
            this.timePerTreatmentLabel.TabIndex = 9;
            this.timePerTreatmentLabel.Text = "Time per Treatment";
            this.timePerTreatmentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.timePerTreatmentLabel.Click += new System.EventHandler(this.label6_Click);
            // 
            // treatmentPerPatientLabel
            // 
            this.treatmentPerPatientLabel.AutoSize = true;
            this.treatmentPerPatientLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentPerPatientLabel.Location = new System.Drawing.Point(3, 132);
            this.treatmentPerPatientLabel.Name = "treatmentPerPatientLabel";
            this.treatmentPerPatientLabel.Size = new System.Drawing.Size(170, 44);
            this.treatmentPerPatientLabel.TabIndex = 7;
            this.treatmentPerPatientLabel.Text = "Treatment Per Patient";
            this.treatmentPerPatientLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // numberOfPatientsLabel
            // 
            this.numberOfPatientsLabel.AutoSize = true;
            this.numberOfPatientsLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numberOfPatientsLabel.Location = new System.Drawing.Point(3, 88);
            this.numberOfPatientsLabel.Name = "numberOfPatientsLabel";
            this.numberOfPatientsLabel.Size = new System.Drawing.Size(170, 44);
            this.numberOfPatientsLabel.TabIndex = 6;
            this.numberOfPatientsLabel.Text = "Number of Patients";
            this.numberOfPatientsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // numberOfPatientsValue
            // 
            this.numberOfPatientsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.numberOfPatientsValue.Location = new System.Drawing.Point(179, 100);
            this.numberOfPatientsValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.numberOfPatientsValue.Name = "numberOfPatientsValue";
            this.numberOfPatientsValue.ReadOnly = true;
            this.numberOfPatientsValue.Size = new System.Drawing.Size(104, 20);
            this.numberOfPatientsValue.TabIndex = 5;
            // 
            // timeBetweenPatientsValue
            // 
            this.timeBetweenPatientsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timeBetweenPatientsValue.Location = new System.Drawing.Point(179, 56);
            this.timeBetweenPatientsValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.timeBetweenPatientsValue.Name = "timeBetweenPatientsValue";
            this.timeBetweenPatientsValue.ReadOnly = true;
            this.timeBetweenPatientsValue.Size = new System.Drawing.Size(104, 20);
            this.timeBetweenPatientsValue.TabIndex = 3;
            // 
            // averageEntryTimePerPatientLabel
            // 
            this.averageEntryTimePerPatientLabel.AutoSize = true;
            this.averageEntryTimePerPatientLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.averageEntryTimePerPatientLabel.Location = new System.Drawing.Point(3, 0);
            this.averageEntryTimePerPatientLabel.Name = "averageEntryTimePerPatientLabel";
            this.averageEntryTimePerPatientLabel.Size = new System.Drawing.Size(170, 44);
            this.averageEntryTimePerPatientLabel.TabIndex = 0;
            this.averageEntryTimePerPatientLabel.Text = "Average Entry Time Per Patient";
            this.averageEntryTimePerPatientLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // timeBetweenPatientsLabel
            // 
            this.timeBetweenPatientsLabel.AutoSize = true;
            this.timeBetweenPatientsLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timeBetweenPatientsLabel.Location = new System.Drawing.Point(3, 44);
            this.timeBetweenPatientsLabel.Name = "timeBetweenPatientsLabel";
            this.timeBetweenPatientsLabel.Size = new System.Drawing.Size(170, 44);
            this.timeBetweenPatientsLabel.TabIndex = 1;
            this.timeBetweenPatientsLabel.Text = "Time Between Patients";
            this.timeBetweenPatientsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // averageEntryTimePerPatientValue
            // 
            this.averageEntryTimePerPatientValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.averageEntryTimePerPatientValue.Location = new System.Drawing.Point(179, 12);
            this.averageEntryTimePerPatientValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.averageEntryTimePerPatientValue.Name = "averageEntryTimePerPatientValue";
            this.averageEntryTimePerPatientValue.ReadOnly = true;
            this.averageEntryTimePerPatientValue.Size = new System.Drawing.Size(104, 20);
            this.averageEntryTimePerPatientValue.TabIndex = 2;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.balancingRoomList);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox3.Location = new System.Drawing.Point(3, 3);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(144, 648);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Room List";
            // 
            // balancingRoomList
            // 
            this.balancingRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.balancingRoomList.FormattingEnabled = true;
            this.balancingRoomList.Location = new System.Drawing.Point(3, 16);
            this.balancingRoomList.Name = "balancingRoomList";
            this.balancingRoomList.Size = new System.Drawing.Size(138, 629);
            this.balancingRoomList.TabIndex = 0;
            this.balancingRoomList.Click += new System.EventHandler(this.OnBalancingCategorySelected);
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.tableLayoutPanel10);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox4.Location = new System.Drawing.Point(153, 3);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(244, 648);
            this.groupBox4.TabIndex = 1;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Difficulty Modifier";
            // 
            // tableLayoutPanel10
            // 
            this.tableLayoutPanel10.ColumnCount = 1;
            this.tableLayoutPanel10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel10.Controls.Add(this.difficultyModifierList, 0, 0);
            this.tableLayoutPanel10.Controls.Add(this.tableLayoutPanel13, 0, 1);
            this.tableLayoutPanel10.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel10.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel10.Name = "tableLayoutPanel10";
            this.tableLayoutPanel10.RowCount = 2;
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel10.Size = new System.Drawing.Size(238, 629);
            this.tableLayoutPanel10.TabIndex = 0;
            // 
            // difficultyModifierList
            // 
            this.difficultyModifierList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.difficultyModifierList.FormattingEnabled = true;
            this.difficultyModifierList.Location = new System.Drawing.Point(3, 3);
            this.difficultyModifierList.Name = "difficultyModifierList";
            this.difficultyModifierList.Size = new System.Drawing.Size(232, 583);
            this.difficultyModifierList.TabIndex = 0;
            this.difficultyModifierList.SelectedIndexChanged += new System.EventHandler(this.OnDifficultyModifierSelected);
            // 
            // tableLayoutPanel13
            // 
            this.tableLayoutPanel13.ColumnCount = 3;
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33332F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel13.Controls.Add(this.buttonAddDiffModifier, 0, 0);
            this.tableLayoutPanel13.Controls.Add(this.buttonRemoveDiffModifier, 1, 0);
            this.tableLayoutPanel13.Controls.Add(this.diffModifierValue, 2, 0);
            this.tableLayoutPanel13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel13.Location = new System.Drawing.Point(3, 592);
            this.tableLayoutPanel13.Name = "tableLayoutPanel13";
            this.tableLayoutPanel13.RowCount = 1;
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            this.tableLayoutPanel13.Size = new System.Drawing.Size(232, 34);
            this.tableLayoutPanel13.TabIndex = 1;
            // 
            // buttonAddDiffModifier
            // 
            this.buttonAddDiffModifier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonAddDiffModifier.Location = new System.Drawing.Point(3, 3);
            this.buttonAddDiffModifier.MaximumSize = new System.Drawing.Size(0, 20);
            this.buttonAddDiffModifier.Name = "buttonAddDiffModifier";
            this.buttonAddDiffModifier.Size = new System.Drawing.Size(71, 20);
            this.buttonAddDiffModifier.TabIndex = 0;
            this.buttonAddDiffModifier.Text = "Add";
            this.buttonAddDiffModifier.UseVisualStyleBackColor = true;
            this.buttonAddDiffModifier.Click += new System.EventHandler(this.ButtonAddDiffModifier_Click);
            // 
            // buttonRemoveDiffModifier
            // 
            this.buttonRemoveDiffModifier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonRemoveDiffModifier.Location = new System.Drawing.Point(80, 3);
            this.buttonRemoveDiffModifier.MaximumSize = new System.Drawing.Size(0, 20);
            this.buttonRemoveDiffModifier.Name = "buttonRemoveDiffModifier";
            this.buttonRemoveDiffModifier.Size = new System.Drawing.Size(71, 20);
            this.buttonRemoveDiffModifier.TabIndex = 1;
            this.buttonRemoveDiffModifier.Text = "Remove";
            this.buttonRemoveDiffModifier.UseVisualStyleBackColor = true;
            this.buttonRemoveDiffModifier.Click += new System.EventHandler(this.ButtonRemoveDiffModifier_Click);
            // 
            // diffModifierValue
            // 
            this.diffModifierValue.DecimalPlaces = 1;
            this.diffModifierValue.Increment = new decimal(new int[] {
            5,
            0,
            0,
            65536});
            this.diffModifierValue.Location = new System.Drawing.Point(157, 3);
            this.diffModifierValue.Name = "diffModifierValue";
            this.diffModifierValue.Size = new System.Drawing.Size(72, 20);
            this.diffModifierValue.TabIndex = 2;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.tableLayoutPanel12);
            this.groupBox5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox5.Location = new System.Drawing.Point(701, 3);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(285, 648);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Global Values";
            // 
            // tableLayoutPanel12
            // 
            this.tableLayoutPanel12.ColumnCount = 2;
            this.tableLayoutPanel12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61.76471F));
            this.tableLayoutPanel12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38.23529F));
            this.tableLayoutPanel12.Controls.Add(this.difficultyModifierTreatmentsBasedLabel, 0, 0);
            this.tableLayoutPanel12.Controls.Add(this.difficultyModifierTreatmentsBasedValue, 1, 0);
            this.tableLayoutPanel12.Controls.Add(this.startLevelDurationLabel, 0, 1);
            this.tableLayoutPanel12.Controls.Add(this.startLevelDurationValue, 1, 1);
            this.tableLayoutPanel12.Controls.Add(this.timeIncreasePerLevelLabel, 0, 2);
            this.tableLayoutPanel12.Controls.Add(this.timeIncreasePerLevelValue, 1, 2);
            this.tableLayoutPanel12.Controls.Add(this.initialTimePerTreatmentLabel, 0, 5);
            this.tableLayoutPanel12.Controls.Add(this.decreaseTimePerTreatmentLabel, 0, 6);
            this.tableLayoutPanel12.Controls.Add(this.decreaseTimePerTreatmentValue, 1, 6);
            this.tableLayoutPanel12.Controls.Add(this.initialTimePerTreatmentValue, 1, 5);
            this.tableLayoutPanel12.Controls.Add(this.decreaseTimeBetweenPatientsValue, 1, 4);
            this.tableLayoutPanel12.Controls.Add(this.initialTimeBetweenPatientsValue, 1, 3);
            this.tableLayoutPanel12.Controls.Add(this.decreaseTimeBetweenPatientsLabel, 0, 4);
            this.tableLayoutPanel12.Controls.Add(this.initialTimeBetweenPatientsLabel, 0, 3);
            this.tableLayoutPanel12.Controls.Add(this.checkoutPerPatientValue, 1, 8);
            this.tableLayoutPanel12.Controls.Add(this.treatmentMinimumTimeValue, 1, 9);
            this.tableLayoutPanel12.Controls.Add(this.checkoutPerPatientLabel, 0, 8);
            this.tableLayoutPanel12.Controls.Add(this.treatmentMinimumTimelabel, 0, 9);
            this.tableLayoutPanel12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel12.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel12.Name = "tableLayoutPanel12";
            this.tableLayoutPanel12.RowCount = 11;
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel12.Size = new System.Drawing.Size(279, 629);
            this.tableLayoutPanel12.TabIndex = 1;
            this.tableLayoutPanel12.Paint += new System.Windows.Forms.PaintEventHandler(this.tableLayoutPanel12_Paint);
            // 
            // difficultyModifierTreatmentsBasedLabel
            // 
            this.difficultyModifierTreatmentsBasedLabel.AutoSize = true;
            this.difficultyModifierTreatmentsBasedLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.difficultyModifierTreatmentsBasedLabel.Location = new System.Drawing.Point(3, 0);
            this.difficultyModifierTreatmentsBasedLabel.Name = "difficultyModifierTreatmentsBasedLabel";
            this.difficultyModifierTreatmentsBasedLabel.Size = new System.Drawing.Size(166, 44);
            this.difficultyModifierTreatmentsBasedLabel.TabIndex = 0;
            this.difficultyModifierTreatmentsBasedLabel.Text = "DifficultyModifier Treatments Based";
            this.difficultyModifierTreatmentsBasedLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.difficultyModifierTreatmentsBasedLabel.Click += new System.EventHandler(this.label13_Click);
            // 
            // difficultyModifierTreatmentsBasedValue
            // 
            this.difficultyModifierTreatmentsBasedValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.difficultyModifierTreatmentsBasedValue.Location = new System.Drawing.Point(175, 12);
            this.difficultyModifierTreatmentsBasedValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.difficultyModifierTreatmentsBasedValue.Name = "difficultyModifierTreatmentsBasedValue";
            this.difficultyModifierTreatmentsBasedValue.ReadOnly = true;
            this.difficultyModifierTreatmentsBasedValue.Size = new System.Drawing.Size(101, 20);
            this.difficultyModifierTreatmentsBasedValue.TabIndex = 2;
            // 
            // startLevelDurationLabel
            // 
            this.startLevelDurationLabel.AutoSize = true;
            this.startLevelDurationLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.startLevelDurationLabel.Location = new System.Drawing.Point(3, 44);
            this.startLevelDurationLabel.Name = "startLevelDurationLabel";
            this.startLevelDurationLabel.Size = new System.Drawing.Size(166, 44);
            this.startLevelDurationLabel.TabIndex = 1;
            this.startLevelDurationLabel.Text = "StartLevelDuration";
            this.startLevelDurationLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // startLevelDurationValue
            // 
            this.startLevelDurationValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.startLevelDurationValue.Location = new System.Drawing.Point(175, 56);
            this.startLevelDurationValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.startLevelDurationValue.Name = "startLevelDurationValue";
            this.startLevelDurationValue.ReadOnly = true;
            this.startLevelDurationValue.Size = new System.Drawing.Size(101, 20);
            this.startLevelDurationValue.TabIndex = 3;
            // 
            // timeIncreasePerLevelLabel
            // 
            this.timeIncreasePerLevelLabel.AutoSize = true;
            this.timeIncreasePerLevelLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timeIncreasePerLevelLabel.Location = new System.Drawing.Point(3, 88);
            this.timeIncreasePerLevelLabel.Name = "timeIncreasePerLevelLabel";
            this.timeIncreasePerLevelLabel.Size = new System.Drawing.Size(166, 44);
            this.timeIncreasePerLevelLabel.TabIndex = 6;
            this.timeIncreasePerLevelLabel.Text = "TimeIncreasePerLevel";
            this.timeIncreasePerLevelLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // timeIncreasePerLevelValue
            // 
            this.timeIncreasePerLevelValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.timeIncreasePerLevelValue.Location = new System.Drawing.Point(175, 100);
            this.timeIncreasePerLevelValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.timeIncreasePerLevelValue.Name = "timeIncreasePerLevelValue";
            this.timeIncreasePerLevelValue.ReadOnly = true;
            this.timeIncreasePerLevelValue.Size = new System.Drawing.Size(101, 20);
            this.timeIncreasePerLevelValue.TabIndex = 5;
            // 
            // initialTimePerTreatmentLabel
            // 
            this.initialTimePerTreatmentLabel.AutoSize = true;
            this.initialTimePerTreatmentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.initialTimePerTreatmentLabel.Location = new System.Drawing.Point(3, 220);
            this.initialTimePerTreatmentLabel.Name = "initialTimePerTreatmentLabel";
            this.initialTimePerTreatmentLabel.Size = new System.Drawing.Size(166, 44);
            this.initialTimePerTreatmentLabel.TabIndex = 11;
            this.initialTimePerTreatmentLabel.Text = "InitialTimePerTreatment";
            this.initialTimePerTreatmentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // decreaseTimePerTreatmentLabel
            // 
            this.decreaseTimePerTreatmentLabel.AutoSize = true;
            this.decreaseTimePerTreatmentLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decreaseTimePerTreatmentLabel.Location = new System.Drawing.Point(3, 264);
            this.decreaseTimePerTreatmentLabel.Name = "decreaseTimePerTreatmentLabel";
            this.decreaseTimePerTreatmentLabel.Size = new System.Drawing.Size(166, 44);
            this.decreaseTimePerTreatmentLabel.TabIndex = 13;
            this.decreaseTimePerTreatmentLabel.Text = "DecreaseTimePerTreatment";
            this.decreaseTimePerTreatmentLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // decreaseTimePerTreatmentValue
            // 
            this.decreaseTimePerTreatmentValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decreaseTimePerTreatmentValue.Location = new System.Drawing.Point(175, 276);
            this.decreaseTimePerTreatmentValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.decreaseTimePerTreatmentValue.Name = "decreaseTimePerTreatmentValue";
            this.decreaseTimePerTreatmentValue.ReadOnly = true;
            this.decreaseTimePerTreatmentValue.Size = new System.Drawing.Size(101, 20);
            this.decreaseTimePerTreatmentValue.TabIndex = 17;
            // 
            // initialTimePerTreatmentValue
            // 
            this.initialTimePerTreatmentValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.initialTimePerTreatmentValue.Location = new System.Drawing.Point(175, 232);
            this.initialTimePerTreatmentValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.initialTimePerTreatmentValue.Name = "initialTimePerTreatmentValue";
            this.initialTimePerTreatmentValue.ReadOnly = true;
            this.initialTimePerTreatmentValue.Size = new System.Drawing.Size(101, 20);
            this.initialTimePerTreatmentValue.TabIndex = 16;
            // 
            // decreaseTimeBetweenPatientsValue
            // 
            this.decreaseTimeBetweenPatientsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decreaseTimeBetweenPatientsValue.Location = new System.Drawing.Point(175, 188);
            this.decreaseTimeBetweenPatientsValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.decreaseTimeBetweenPatientsValue.Name = "decreaseTimeBetweenPatientsValue";
            this.decreaseTimeBetweenPatientsValue.ReadOnly = true;
            this.decreaseTimeBetweenPatientsValue.Size = new System.Drawing.Size(101, 20);
            this.decreaseTimeBetweenPatientsValue.TabIndex = 15;
            // 
            // initialTimeBetweenPatientsValue
            // 
            this.initialTimeBetweenPatientsValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.initialTimeBetweenPatientsValue.Location = new System.Drawing.Point(175, 144);
            this.initialTimeBetweenPatientsValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.initialTimeBetweenPatientsValue.Name = "initialTimeBetweenPatientsValue";
            this.initialTimeBetweenPatientsValue.ReadOnly = true;
            this.initialTimeBetweenPatientsValue.Size = new System.Drawing.Size(101, 20);
            this.initialTimeBetweenPatientsValue.TabIndex = 14;
            // 
            // decreaseTimeBetweenPatientsLabel
            // 
            this.decreaseTimeBetweenPatientsLabel.AutoSize = true;
            this.decreaseTimeBetweenPatientsLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.decreaseTimeBetweenPatientsLabel.Location = new System.Drawing.Point(3, 176);
            this.decreaseTimeBetweenPatientsLabel.Name = "decreaseTimeBetweenPatientsLabel";
            this.decreaseTimeBetweenPatientsLabel.Size = new System.Drawing.Size(166, 44);
            this.decreaseTimeBetweenPatientsLabel.TabIndex = 9;
            this.decreaseTimeBetweenPatientsLabel.Text = "DecreaseTimeBetweenPatients";
            this.decreaseTimeBetweenPatientsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // initialTimeBetweenPatientsLabel
            // 
            this.initialTimeBetweenPatientsLabel.AutoSize = true;
            this.initialTimeBetweenPatientsLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.initialTimeBetweenPatientsLabel.Location = new System.Drawing.Point(3, 132);
            this.initialTimeBetweenPatientsLabel.Name = "initialTimeBetweenPatientsLabel";
            this.initialTimeBetweenPatientsLabel.Size = new System.Drawing.Size(166, 44);
            this.initialTimeBetweenPatientsLabel.TabIndex = 7;
            this.initialTimeBetweenPatientsLabel.Text = "InitialTimeBetweenPatients";
            this.initialTimeBetweenPatientsLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // checkoutPerPatientValue
            // 
            this.checkoutPerPatientValue.Location = new System.Drawing.Point(175, 320);
            this.checkoutPerPatientValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.checkoutPerPatientValue.Name = "checkoutPerPatientValue";
            this.checkoutPerPatientValue.ReadOnly = true;
            this.checkoutPerPatientValue.Size = new System.Drawing.Size(100, 20);
            this.checkoutPerPatientValue.TabIndex = 22;
            // 
            // treatmentMinimumTimeValue
            // 
            this.treatmentMinimumTimeValue.Location = new System.Drawing.Point(175, 364);
            this.treatmentMinimumTimeValue.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.treatmentMinimumTimeValue.Name = "treatmentMinimumTimeValue";
            this.treatmentMinimumTimeValue.ReadOnly = true;
            this.treatmentMinimumTimeValue.Size = new System.Drawing.Size(100, 20);
            this.treatmentMinimumTimeValue.TabIndex = 23;
            // 
            // checkoutPerPatientLabel
            // 
            this.checkoutPerPatientLabel.AutoSize = true;
            this.checkoutPerPatientLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.checkoutPerPatientLabel.Location = new System.Drawing.Point(3, 308);
            this.checkoutPerPatientLabel.Name = "checkoutPerPatientLabel";
            this.checkoutPerPatientLabel.Size = new System.Drawing.Size(166, 44);
            this.checkoutPerPatientLabel.TabIndex = 24;
            this.checkoutPerPatientLabel.Text = "CheckoutPerPatient";
            this.checkoutPerPatientLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // treatmentMinimumTimelabel
            // 
            this.treatmentMinimumTimelabel.AutoSize = true;
            this.treatmentMinimumTimelabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentMinimumTimelabel.Location = new System.Drawing.Point(3, 352);
            this.treatmentMinimumTimelabel.Name = "treatmentMinimumTimelabel";
            this.treatmentMinimumTimelabel.Size = new System.Drawing.Size(166, 44);
            this.treatmentMinimumTimelabel.TabIndex = 25;
            this.treatmentMinimumTimelabel.Text = "TreatmentMinimumTime";
            this.treatmentMinimumTimelabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 1;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Controls.Add(this.flowLayoutPanel1, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.tabControl1, 0, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 2;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(1007, 730);
            this.tableLayoutPanel4.TabIndex = 1;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoSize = true;
            this.flowLayoutPanel1.Controls.Add(this.cancelButton);
            this.flowLayoutPanel1.Controls.Add(this.saveButton);
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(2, 692);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.flowLayoutPanel1.MaximumSize = new System.Drawing.Size(0, 41);
            this.flowLayoutPanel1.MinimumSize = new System.Drawing.Size(0, 32);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.flowLayoutPanel1.Size = new System.Drawing.Size(1003, 36);
            this.flowLayoutPanel1.TabIndex = 2;
            // 
            // cancelButton
            // 
            this.cancelButton.Location = new System.Drawing.Point(945, 4);
            this.cancelButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.cancelButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(56, 24);
            this.cancelButton.TabIndex = 1;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.cancelButton.Click += new System.EventHandler(this.canelButton_Click);
            // 
            // saveButton
            // 
            this.saveButton.Location = new System.Drawing.Point(885, 4);
            this.saveButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.saveButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.saveButton.Name = "saveButton";
            this.saveButton.Size = new System.Drawing.Size(56, 24);
            this.saveButton.TabIndex = 0;
            this.saveButton.Text = "Save";
            this.saveButton.UseVisualStyleBackColor = true;
            this.saveButton.Click += new System.EventHandler(this.saveButton_Click);
            // 
            // windowSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1007, 730);
            this.Controls.Add(this.tableLayoutPanel4);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.MinimumSize = new System.Drawing.Size(604, 495);
            this.Name = "windowSettings";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Settings";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.projectDirectoryLayout.ResumeLayout(false);
            this.projectDirectoryLayout.PerformLayout();
            this.tabPatientTypes.ResumeLayout(false);
            this.patientTypesLayout.ResumeLayout(false);
            this.patientTypeAutoGenerated.ResumeLayout(false);
            this.patientTypeAutoGenerated.PerformLayout();
            this.patientTypeRoomGroup.ResumeLayout(false);
            this.PatientTypeChoicesGroup.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.patientTypeOtherChoicesGroup.ResumeLayout(false);
            this.tableLayoutPanel7.ResumeLayout(false);
            this.patientTypeMaleChoicesGroup.ResumeLayout(false);
            this.patientTypeFemaleChoicesGroup.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.treatmentRoomListGroup.ResumeLayout(false);
            this.tableLayoutPanel8.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.treatmentDataGridView)).EndInit();
            this.flowLayoutPanel2.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tableLayoutPanel9.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.tableLayoutPanel11.ResumeLayout(false);
            this.tableLayoutPanel11.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.tableLayoutPanel10.ResumeLayout(false);
            this.tableLayoutPanel13.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.diffModifierValue)).EndInit();
            this.groupBox5.ResumeLayout(false);
            this.tableLayoutPanel12.ResumeLayout(false);
            this.tableLayoutPanel12.PerformLayout();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label projectDirectoryLabel;
        private System.Windows.Forms.FlowLayoutPanel projectDirectoryLayout;
        private System.Windows.Forms.TextBox projectDirectoryPathText;
        private System.Windows.Forms.Button projectDirectoryBrowseButton;
        private System.Windows.Forms.TabPage tabPatientTypes;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TableLayoutPanel patientTypesLayout;
        private System.Windows.Forms.GroupBox patientTypeAutoGenerated;
        private System.Windows.Forms.GroupBox patientTypeRoomGroup;
        private System.Windows.Forms.GroupBox PatientTypeChoicesGroup;
        private System.Windows.Forms.ListBox patientTypeRoomList;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button saveButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.GroupBox patientTypeOtherChoicesGroup;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
        private System.Windows.Forms.GroupBox patientTypeMaleChoicesGroup;
        private System.Windows.Forms.GroupBox patientTypeFemaleChoicesGroup;
        private System.Windows.Forms.TextBox patientTypeListAutoGeneratedText;
        private System.Windows.Forms.CheckedListBox patientTypeMaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeFemaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeOtherCheckList;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.GroupBox treatmentRoomListGroup;
        private System.Windows.Forms.ListBox treatmentRoomList;
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel8;
        private System.Windows.Forms.DataGridView treatmentDataGridView;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private System.Windows.Forms.Button treatmentRowButtonAdd;
        private System.Windows.Forms.Button treatmentRowButtonRemove;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel9;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel11;
        private System.Windows.Forms.Label timePerTreatmentLabel;
        private System.Windows.Forms.Label treatmentPerPatientLabel;
        private System.Windows.Forms.Label numberOfPatientsLabel;
        private System.Windows.Forms.TextBox numberOfPatientsValue;
        private System.Windows.Forms.TextBox timeBetweenPatientsValue;
        private System.Windows.Forms.Label averageEntryTimePerPatientLabel;
        private System.Windows.Forms.Label timeBetweenPatientsLabel;
        private System.Windows.Forms.TextBox averageEntryTimePerPatientValue;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.ListBox balancingRoomList;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel10;
        private System.Windows.Forms.ListBox difficultyModifierList;
        private System.Windows.Forms.Label milliSecondsPerLevelLabel;
        private System.Windows.Forms.TextBox minutesPerLevelValue;
        private System.Windows.Forms.TextBox milliSecondsPerLevelValue;
        private System.Windows.Forms.TextBox timePerTreatmentValue;
        private System.Windows.Forms.TextBox treatmentPerPatientValue;
        private System.Windows.Forms.Label minutesPerLevelLabel;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel12;
        private System.Windows.Forms.TextBox decreaseTimePerTreatmentValue;
        private System.Windows.Forms.TextBox initialTimePerTreatmentValue;
        private System.Windows.Forms.TextBox decreaseTimeBetweenPatientsValue;
        private System.Windows.Forms.TextBox initialTimeBetweenPatientsValue;
        private System.Windows.Forms.Label decreaseTimePerTreatmentLabel;
        private System.Windows.Forms.Label initialTimePerTreatmentLabel;
        private System.Windows.Forms.Label decreaseTimeBetweenPatientsLabel;
        private System.Windows.Forms.Label initialTimeBetweenPatientsLabel;
        private System.Windows.Forms.Label timeIncreasePerLevelLabel;
        private System.Windows.Forms.TextBox timeIncreasePerLevelValue;
        private System.Windows.Forms.TextBox startLevelDurationValue;
        private System.Windows.Forms.Label difficultyModifierTreatmentsBasedLabel;
        private System.Windows.Forms.Label startLevelDurationLabel;
        private System.Windows.Forms.TextBox difficultyModifierTreatmentsBasedValue;
        private System.Windows.Forms.TextBox checkoutPerPatientValue;
        private System.Windows.Forms.TextBox treatmentMinimumTimeValue;
        private System.Windows.Forms.Label checkoutPerPatientLabel;
        private System.Windows.Forms.Label treatmentMinimumTimelabel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel13;
        private System.Windows.Forms.Button buttonAddDiffModifier;
        private System.Windows.Forms.Button buttonRemoveDiffModifier;
        private System.Windows.Forms.NumericUpDown diffModifierValue;
        private System.Windows.Forms.DataGridViewCheckBoxColumn treatmentSelect;
        private System.Windows.Forms.DataGridViewTextBoxColumn treatmentName;
        private System.Windows.Forms.DataGridViewComboBoxColumn difficultyUnlocked;
        private System.Windows.Forms.DataGridViewTextBoxColumn heartsValue;
        private System.Windows.Forms.DataGridViewTextBoxColumn weight;
        private System.Windows.Forms.DataGridViewTextBoxColumn weightPercentage;
        private System.Windows.Forms.DataGridViewCheckBoxColumn gesture;
        private System.Windows.Forms.DataGridViewCheckBoxColumn alwaysLast;
        private System.Windows.Forms.DataGridViewButtonColumn colorButton;
        private System.Windows.Forms.DataGridViewTextBoxColumn colorValue;
    }
}