namespace Windows
{
    partial class windowSettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.projectDirectoryLabel = new System.Windows.Forms.Label();
            this.projectDirectoryLayout = new System.Windows.Forms.FlowLayoutPanel();
            this.projectDirectoryPathText = new System.Windows.Forms.TextBox();
            this.projectDirectoryBrowseButton = new System.Windows.Forms.Button();
            this.tabPatientTypes = new System.Windows.Forms.TabPage();
            this.patientTypesLayout = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeAutoGenerated = new System.Windows.Forms.GroupBox();
            this.patientTypeListAutoGeneratedText = new System.Windows.Forms.TextBox();
            this.patientTypeRoomGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeRoomList = new System.Windows.Forms.ListBox();
            this.PatientTypeChoicesGroup = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeOtherChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeOtherCheckList = new System.Windows.Forms.CheckedListBox();
            this.tableLayoutPanel7 = new System.Windows.Forms.TableLayoutPanel();
            this.patientTypeMaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeMaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.patientTypeFemaleChoicesGroup = new System.Windows.Forms.GroupBox();
            this.patientTypeFemaleCheckList = new System.Windows.Forms.CheckedListBox();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.treatmentRoomListGroup = new System.Windows.Forms.GroupBox();
            this.treatmentRoomList = new System.Windows.Forms.ListBox();
            this.tableLayoutPanel8 = new System.Windows.Forms.TableLayoutPanel();
            this.treatmentDataGridView = new System.Windows.Forms.DataGridView();
            this.treatmentSelect = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.treatmentType = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.difficultyUnlocked = new System.Windows.Forms.DataGridViewComboBoxColumn();
            this.heartsValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.weight = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.weightPercentage = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.gesture = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.alwaysLast = new System.Windows.Forms.DataGridViewCheckBoxColumn();
            this.color = new System.Windows.Forms.DataGridViewButtonColumn();
            this.colorValue = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.button1 = new System.Windows.Forms.Button();
            this.button2 = new System.Windows.Forms.Button();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.tableLayoutPanel9 = new System.Windows.Forms.TableLayoutPanel();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel11 = new System.Windows.Forms.TableLayoutPanel();
            this.textBox7 = new System.Windows.Forms.TextBox();
            this.textBox6 = new System.Windows.Forms.TextBox();
            this.textBox5 = new System.Windows.Forms.TextBox();
            this.textBox3 = new System.Windows.Forms.TextBox();
            this.label10 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.textBox4 = new System.Windows.Forms.TextBox();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.balancingRoomList = new System.Windows.Forms.ListBox();
            this.groupBox4 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel10 = new System.Windows.Forms.TableLayoutPanel();
            this.difficultyModifierList = new System.Windows.Forms.ListBox();
            this.tableLayoutPanel13 = new System.Windows.Forms.TableLayoutPanel();
            this.buttonAddDiffModifier = new System.Windows.Forms.Button();
            this.buttonRemoveDiffModifier = new System.Windows.Forms.Button();
            this.diffModifierValue = new System.Windows.Forms.NumericUpDown();
            this.groupBox5 = new System.Windows.Forms.GroupBox();
            this.tableLayoutPanel12 = new System.Windows.Forms.TableLayoutPanel();
            this.textBox8 = new System.Windows.Forms.TextBox();
            this.textBox9 = new System.Windows.Forms.TextBox();
            this.textBox10 = new System.Windows.Forms.TextBox();
            this.textBox11 = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label9 = new System.Windows.Forms.Label();
            this.label11 = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.textBox12 = new System.Windows.Forms.TextBox();
            this.textBox13 = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.textBox14 = new System.Windows.Forms.TextBox();
            this.textBox19 = new System.Windows.Forms.TextBox();
            this.textBox20 = new System.Windows.Forms.TextBox();
            this.label15 = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.cancelButton = new System.Windows.Forms.Button();
            this.saveButton = new System.Windows.Forms.Button();
            this.colorDialog1 = new System.Windows.Forms.ColorDialog();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.projectDirectoryLayout.SuspendLayout();
            this.tabPatientTypes.SuspendLayout();
            this.patientTypesLayout.SuspendLayout();
            this.patientTypeAutoGenerated.SuspendLayout();
            this.patientTypeRoomGroup.SuspendLayout();
            this.PatientTypeChoicesGroup.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            this.patientTypeOtherChoicesGroup.SuspendLayout();
            this.tableLayoutPanel7.SuspendLayout();
            this.patientTypeMaleChoicesGroup.SuspendLayout();
            this.patientTypeFemaleChoicesGroup.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.treatmentRoomListGroup.SuspendLayout();
            this.tableLayoutPanel8.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.treatmentDataGridView)).BeginInit();
            this.flowLayoutPanel2.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tableLayoutPanel9.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.tableLayoutPanel11.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.tableLayoutPanel10.SuspendLayout();
            this.tableLayoutPanel13.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.diffModifierValue)).BeginInit();
            this.groupBox5.SuspendLayout();
            this.tableLayoutPanel12.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.flowLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPatientTypes);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(2, 2);
            this.tabControl1.Margin = new System.Windows.Forms.Padding(2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(1003, 686);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.tableLayoutPanel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Margin = new System.Windows.Forms.Padding(2);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(2);
            this.tabPage1.Size = new System.Drawing.Size(995, 660);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "General";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 656F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(991, 656);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 1;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 15F));
            this.tableLayoutPanel2.Controls.Add(this.groupBox1, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(2, 2);
            this.tableLayoutPanel2.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 4;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(491, 652);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.tableLayoutPanel3);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox1.Location = new System.Drawing.Point(2, 2);
            this.groupBox1.Margin = new System.Windows.Forms.Padding(2);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Padding = new System.Windows.Forms.Padding(2);
            this.groupBox1.Size = new System.Drawing.Size(487, 600);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "HM4 Project Directories";
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLabel, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.projectDirectoryLayout, 0, 1);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(2, 15);
            this.tableLayoutPanel3.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 4;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 16F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(483, 583);
            this.tableLayoutPanel3.TabIndex = 0;
            // 
            // projectDirectoryLabel
            // 
            this.projectDirectoryLabel.AutoSize = true;
            this.projectDirectoryLabel.Location = new System.Drawing.Point(2, 0);
            this.projectDirectoryLabel.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.projectDirectoryLabel.Name = "projectDirectoryLabel";
            this.projectDirectoryLabel.Size = new System.Drawing.Size(173, 13);
            this.projectDirectoryLabel.TabIndex = 0;
            this.projectDirectoryLabel.Text = "Data directory (e.g, \'C:/hm4/data/\')";
            // 
            // projectDirectoryLayout
            // 
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryPathText);
            this.projectDirectoryLayout.Controls.Add(this.projectDirectoryBrowseButton);
            this.projectDirectoryLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryLayout.Location = new System.Drawing.Point(2, 18);
            this.projectDirectoryLayout.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryLayout.Name = "projectDirectoryLayout";
            this.projectDirectoryLayout.Size = new System.Drawing.Size(479, 28);
            this.projectDirectoryLayout.TabIndex = 1;
            // 
            // projectDirectoryPathText
            // 
            this.projectDirectoryPathText.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.projectDirectoryPathText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.projectDirectoryPathText.Location = new System.Drawing.Point(2, 2);
            this.projectDirectoryPathText.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryPathText.MinimumSize = new System.Drawing.Size(2, 25);
            this.projectDirectoryPathText.Name = "projectDirectoryPathText";
            this.projectDirectoryPathText.Size = new System.Drawing.Size(209, 20);
            this.projectDirectoryPathText.TabIndex = 0;
            // 
            // projectDirectoryBrowseButton
            // 
            this.projectDirectoryBrowseButton.Location = new System.Drawing.Point(215, 2);
            this.projectDirectoryBrowseButton.Margin = new System.Windows.Forms.Padding(2);
            this.projectDirectoryBrowseButton.MinimumSize = new System.Drawing.Size(0, 20);
            this.projectDirectoryBrowseButton.Name = "projectDirectoryBrowseButton";
            this.projectDirectoryBrowseButton.Size = new System.Drawing.Size(56, 24);
            this.projectDirectoryBrowseButton.TabIndex = 1;
            this.projectDirectoryBrowseButton.Text = "Browse";
            this.projectDirectoryBrowseButton.UseVisualStyleBackColor = true;
            this.projectDirectoryBrowseButton.Click += new System.EventHandler(this.button1_Click);
            // 
            // tabPatientTypes
            // 
            this.tabPatientTypes.Controls.Add(this.patientTypesLayout);
            this.tabPatientTypes.Location = new System.Drawing.Point(4, 22);
            this.tabPatientTypes.Margin = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Name = "tabPatientTypes";
            this.tabPatientTypes.Padding = new System.Windows.Forms.Padding(2);
            this.tabPatientTypes.Size = new System.Drawing.Size(995, 660);
            this.tabPatientTypes.TabIndex = 1;
            this.tabPatientTypes.Text = "Patient Types";
            this.tabPatientTypes.UseVisualStyleBackColor = true;
            // 
            // patientTypesLayout
            // 
            this.patientTypesLayout.ColumnCount = 3;
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 66.05556F));
            this.patientTypesLayout.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.94445F));
            this.patientTypesLayout.Controls.Add(this.patientTypeAutoGenerated, 2, 0);
            this.patientTypesLayout.Controls.Add(this.patientTypeRoomGroup, 0, 0);
            this.patientTypesLayout.Controls.Add(this.PatientTypeChoicesGroup, 1, 0);
            this.patientTypesLayout.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypesLayout.Location = new System.Drawing.Point(2, 2);
            this.patientTypesLayout.Name = "patientTypesLayout";
            this.patientTypesLayout.RowCount = 1;
            this.patientTypesLayout.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.patientTypesLayout.Size = new System.Drawing.Size(991, 656);
            this.patientTypesLayout.TabIndex = 3;
            // 
            // patientTypeAutoGenerated
            // 
            this.patientTypeAutoGenerated.Controls.Add(this.patientTypeListAutoGeneratedText);
            this.patientTypeAutoGenerated.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeAutoGenerated.Location = new System.Drawing.Point(708, 3);
            this.patientTypeAutoGenerated.Name = "patientTypeAutoGenerated";
            this.patientTypeAutoGenerated.Size = new System.Drawing.Size(280, 650);
            this.patientTypeAutoGenerated.TabIndex = 2;
            this.patientTypeAutoGenerated.TabStop = false;
            this.patientTypeAutoGenerated.Text = "Current Patient List";
            // 
            // patientTypeListAutoGeneratedText
            // 
            this.patientTypeListAutoGeneratedText.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeListAutoGeneratedText.Location = new System.Drawing.Point(3, 16);
            this.patientTypeListAutoGeneratedText.Multiline = true;
            this.patientTypeListAutoGeneratedText.Name = "patientTypeListAutoGeneratedText";
            this.patientTypeListAutoGeneratedText.ReadOnly = true;
            this.patientTypeListAutoGeneratedText.Size = new System.Drawing.Size(274, 631);
            this.patientTypeListAutoGeneratedText.TabIndex = 0;
            // 
            // patientTypeRoomGroup
            // 
            this.patientTypeRoomGroup.Controls.Add(this.patientTypeRoomList);
            this.patientTypeRoomGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeRoomGroup.Name = "patientTypeRoomGroup";
            this.patientTypeRoomGroup.Size = new System.Drawing.Size(144, 650);
            this.patientTypeRoomGroup.TabIndex = 0;
            this.patientTypeRoomGroup.TabStop = false;
            this.patientTypeRoomGroup.Text = "Room List";
            // 
            // patientTypeRoomList
            // 
            this.patientTypeRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeRoomList.FormattingEnabled = true;
            this.patientTypeRoomList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeRoomList.Name = "patientTypeRoomList";
            this.patientTypeRoomList.Size = new System.Drawing.Size(138, 631);
            this.patientTypeRoomList.TabIndex = 0;
            this.patientTypeRoomList.SelectedValueChanged += new System.EventHandler(this.onPatientTypeCategorySelected);
            // 
            // PatientTypeChoicesGroup
            // 
            this.PatientTypeChoicesGroup.Controls.Add(this.tableLayoutPanel6);
            this.PatientTypeChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.PatientTypeChoicesGroup.Location = new System.Drawing.Point(153, 3);
            this.PatientTypeChoicesGroup.Name = "PatientTypeChoicesGroup";
            this.PatientTypeChoicesGroup.Size = new System.Drawing.Size(549, 650);
            this.PatientTypeChoicesGroup.TabIndex = 1;
            this.PatientTypeChoicesGroup.TabStop = false;
            this.PatientTypeChoicesGroup.Text = "Patient Types";
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.ColumnCount = 1;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel6.Controls.Add(this.patientTypeOtherChoicesGroup, 0, 1);
            this.tableLayoutPanel6.Controls.Add(this.tableLayoutPanel7, 0, 0);
            this.tableLayoutPanel6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel6.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 2;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 67.19493F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 32.80507F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(543, 631);
            this.tableLayoutPanel6.TabIndex = 0;
            // 
            // patientTypeOtherChoicesGroup
            // 
            this.patientTypeOtherChoicesGroup.Controls.Add(this.patientTypeOtherCheckList);
            this.patientTypeOtherChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherChoicesGroup.Location = new System.Drawing.Point(3, 427);
            this.patientTypeOtherChoicesGroup.Name = "patientTypeOtherChoicesGroup";
            this.patientTypeOtherChoicesGroup.Size = new System.Drawing.Size(537, 201);
            this.patientTypeOtherChoicesGroup.TabIndex = 1;
            this.patientTypeOtherChoicesGroup.TabStop = false;
            this.patientTypeOtherChoicesGroup.Text = "Other Patients";
            // 
            // patientTypeOtherCheckList
            // 
            this.patientTypeOtherCheckList.CheckOnClick = true;
            this.patientTypeOtherCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeOtherCheckList.FormattingEnabled = true;
            this.patientTypeOtherCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeOtherCheckList.MultiColumn = true;
            this.patientTypeOtherCheckList.Name = "patientTypeOtherCheckList";
            this.patientTypeOtherCheckList.Size = new System.Drawing.Size(531, 182);
            this.patientTypeOtherCheckList.TabIndex = 0;
            // 
            // tableLayoutPanel7
            // 
            this.tableLayoutPanel7.ColumnCount = 2;
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel7.Controls.Add(this.patientTypeMaleChoicesGroup, 0, 0);
            this.tableLayoutPanel7.Controls.Add(this.patientTypeFemaleChoicesGroup, 1, 0);
            this.tableLayoutPanel7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel7.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel7.Name = "tableLayoutPanel7";
            this.tableLayoutPanel7.RowCount = 1;
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel7.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 418F));
            this.tableLayoutPanel7.Size = new System.Drawing.Size(537, 418);
            this.tableLayoutPanel7.TabIndex = 2;
            // 
            // patientTypeMaleChoicesGroup
            // 
            this.patientTypeMaleChoicesGroup.Controls.Add(this.patientTypeMaleCheckList);
            this.patientTypeMaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleChoicesGroup.Location = new System.Drawing.Point(3, 3);
            this.patientTypeMaleChoicesGroup.Name = "patientTypeMaleChoicesGroup";
            this.patientTypeMaleChoicesGroup.Size = new System.Drawing.Size(262, 412);
            this.patientTypeMaleChoicesGroup.TabIndex = 0;
            this.patientTypeMaleChoicesGroup.TabStop = false;
            this.patientTypeMaleChoicesGroup.Text = "Male Patients";
            // 
            // patientTypeMaleCheckList
            // 
            this.patientTypeMaleCheckList.CheckOnClick = true;
            this.patientTypeMaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeMaleCheckList.FormattingEnabled = true;
            this.patientTypeMaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeMaleCheckList.Name = "patientTypeMaleCheckList";
            this.patientTypeMaleCheckList.Size = new System.Drawing.Size(256, 393);
            this.patientTypeMaleCheckList.Sorted = true;
            this.patientTypeMaleCheckList.TabIndex = 0;
            // 
            // patientTypeFemaleChoicesGroup
            // 
            this.patientTypeFemaleChoicesGroup.Controls.Add(this.patientTypeFemaleCheckList);
            this.patientTypeFemaleChoicesGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleChoicesGroup.Location = new System.Drawing.Point(271, 3);
            this.patientTypeFemaleChoicesGroup.Name = "patientTypeFemaleChoicesGroup";
            this.patientTypeFemaleChoicesGroup.Size = new System.Drawing.Size(263, 412);
            this.patientTypeFemaleChoicesGroup.TabIndex = 1;
            this.patientTypeFemaleChoicesGroup.TabStop = false;
            this.patientTypeFemaleChoicesGroup.Text = "Female Patients";
            // 
            // patientTypeFemaleCheckList
            // 
            this.patientTypeFemaleCheckList.CheckOnClick = true;
            this.patientTypeFemaleCheckList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.patientTypeFemaleCheckList.FormattingEnabled = true;
            this.patientTypeFemaleCheckList.Location = new System.Drawing.Point(3, 16);
            this.patientTypeFemaleCheckList.Name = "patientTypeFemaleCheckList";
            this.patientTypeFemaleCheckList.Size = new System.Drawing.Size(257, 393);
            this.patientTypeFemaleCheckList.TabIndex = 0;
            // 
            // tabPage3
            // 
            this.tabPage3.Controls.Add(this.tableLayoutPanel5);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage3.Size = new System.Drawing.Size(995, 660);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "Treatments";
            this.tabPage3.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Controls.Add(this.treatmentRoomListGroup, 0, 0);
            this.tableLayoutPanel5.Controls.Add(this.tableLayoutPanel8, 1, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(989, 654);
            this.tableLayoutPanel5.TabIndex = 4;
            // 
            // treatmentRoomListGroup
            // 
            this.treatmentRoomListGroup.Controls.Add(this.treatmentRoomList);
            this.treatmentRoomListGroup.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentRoomListGroup.Location = new System.Drawing.Point(3, 3);
            this.treatmentRoomListGroup.Name = "treatmentRoomListGroup";
            this.treatmentRoomListGroup.Size = new System.Drawing.Size(144, 648);
            this.treatmentRoomListGroup.TabIndex = 0;
            this.treatmentRoomListGroup.TabStop = false;
            this.treatmentRoomListGroup.Text = "Room List";
            // 
            // treatmentRoomList
            // 
            this.treatmentRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentRoomList.FormattingEnabled = true;
            this.treatmentRoomList.Location = new System.Drawing.Point(3, 16);
            this.treatmentRoomList.Name = "treatmentRoomList";
            this.treatmentRoomList.Size = new System.Drawing.Size(138, 629);
            this.treatmentRoomList.TabIndex = 0;
            // 
            // tableLayoutPanel8
            // 
            this.tableLayoutPanel8.ColumnCount = 1;
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel8.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel8.Controls.Add(this.treatmentDataGridView, 0, 0);
            this.tableLayoutPanel8.Controls.Add(this.flowLayoutPanel2, 0, 1);
            this.tableLayoutPanel8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel8.Location = new System.Drawing.Point(153, 3);
            this.tableLayoutPanel8.Name = "tableLayoutPanel8";
            this.tableLayoutPanel8.RowCount = 2;
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel8.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel8.Size = new System.Drawing.Size(833, 648);
            this.tableLayoutPanel8.TabIndex = 1;
            // 
            // treatmentDataGridView
            // 
            this.treatmentDataGridView.AllowUserToResizeRows = false;
            this.treatmentDataGridView.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.treatmentDataGridView.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.treatmentDataGridView.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.treatmentSelect,
            this.treatmentType,
            this.difficultyUnlocked,
            this.heartsValue,
            this.weight,
            this.weightPercentage,
            this.gesture,
            this.alwaysLast,
            this.color,
            this.colorValue});
            this.treatmentDataGridView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.treatmentDataGridView.Location = new System.Drawing.Point(3, 3);
            this.treatmentDataGridView.MultiSelect = false;
            this.treatmentDataGridView.Name = "treatmentDataGridView";
            this.treatmentDataGridView.RowHeadersVisible = false;
            this.treatmentDataGridView.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.CellSelect;
            this.treatmentDataGridView.Size = new System.Drawing.Size(827, 602);
            this.treatmentDataGridView.TabIndex = 2;
            // 
            // treatmentSelect
            // 
            this.treatmentSelect.HeaderText = "";
            this.treatmentSelect.Name = "treatmentSelect";
            this.treatmentSelect.Width = 30;
            // 
            // treatmentType
            // 
            this.treatmentType.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
            this.treatmentType.HeaderText = "TreatmentType";
            this.treatmentType.Name = "treatmentType";
            // 
            // difficultyUnlocked
            // 
            this.difficultyUnlocked.HeaderText = "Difficulty Unlocked";
            this.difficultyUnlocked.Name = "difficultyUnlocked";
            // 
            // heartsValue
            // 
            this.heartsValue.HeaderText = "Hearts Value";
            this.heartsValue.Name = "heartsValue";
            // 
            // weight
            // 
            this.weight.HeaderText = "Weight";
            this.weight.Name = "weight";
            this.weight.Width = 50;
            // 
            // weightPercentage
            // 
            this.weightPercentage.HeaderText = "";
            this.weightPercentage.Name = "weightPercentage";
            this.weightPercentage.ReadOnly = true;
            this.weightPercentage.Width = 50;
            // 
            // gesture
            // 
            this.gesture.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.gesture.HeaderText = "Gesture";
            this.gesture.Name = "gesture";
            this.gesture.Width = 50;
            // 
            // alwaysLast
            // 
            this.alwaysLast.AutoSizeMode = System.Windows.Forms.DataGridViewAutoSizeColumnMode.ColumnHeader;
            this.alwaysLast.HeaderText = "Always Last";
            this.alwaysLast.Name = "alwaysLast";
            this.alwaysLast.Width = 69;
            // 
            // color
            // 
            this.color.HeaderText = "Color";
            this.color.Name = "color";
            // 
            // colorValue
            // 
            this.colorValue.HeaderText = "Value";
            this.colorValue.Name = "colorValue";
            this.colorValue.ReadOnly = true;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.Controls.Add(this.button1);
            this.flowLayoutPanel2.Controls.Add(this.button2);
            this.flowLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel2.Location = new System.Drawing.Point(3, 611);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(827, 34);
            this.flowLayoutPanel2.TabIndex = 3;
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(3, 3);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 23);
            this.button1.TabIndex = 0;
            this.button1.Text = "Add";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click_1);
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(84, 3);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(75, 23);
            this.button2.TabIndex = 1;
            this.button2.Text = "Remove";
            this.button2.UseVisualStyleBackColor = true;
            // 
            // tabPage4
            // 
            this.tabPage4.Controls.Add(this.tableLayoutPanel9);
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage4.Size = new System.Drawing.Size(995, 660);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "Balancing";
            this.tabPage4.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanel9
            // 
            this.tableLayoutPanel9.ColumnCount = 4;
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 150F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 250F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50.7054F));
            this.tableLayoutPanel9.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 49.2946F));
            this.tableLayoutPanel9.Controls.Add(this.groupBox2, 2, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox3, 0, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox4, 1, 0);
            this.tableLayoutPanel9.Controls.Add(this.groupBox5, 3, 0);
            this.tableLayoutPanel9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel9.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel9.Name = "tableLayoutPanel9";
            this.tableLayoutPanel9.RowCount = 1;
            this.tableLayoutPanel9.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel9.Size = new System.Drawing.Size(989, 654);
            this.tableLayoutPanel9.TabIndex = 4;
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.tableLayoutPanel11);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox2.Location = new System.Drawing.Point(403, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(292, 648);
            this.groupBox2.TabIndex = 2;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Calculated Values";
            // 
            // tableLayoutPanel11
            // 
            this.tableLayoutPanel11.ColumnCount = 2;
            this.tableLayoutPanel11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61.76471F));
            this.tableLayoutPanel11.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38.23529F));
            this.tableLayoutPanel11.Controls.Add(this.textBox7, 1, 6);
            this.tableLayoutPanel11.Controls.Add(this.textBox6, 1, 5);
            this.tableLayoutPanel11.Controls.Add(this.textBox5, 1, 4);
            this.tableLayoutPanel11.Controls.Add(this.textBox3, 1, 3);
            this.tableLayoutPanel11.Controls.Add(this.label10, 0, 6);
            this.tableLayoutPanel11.Controls.Add(this.label8, 0, 5);
            this.tableLayoutPanel11.Controls.Add(this.label6, 0, 4);
            this.tableLayoutPanel11.Controls.Add(this.label4, 0, 3);
            this.tableLayoutPanel11.Controls.Add(this.label3, 0, 2);
            this.tableLayoutPanel11.Controls.Add(this.textBox4, 1, 2);
            this.tableLayoutPanel11.Controls.Add(this.textBox2, 1, 1);
            this.tableLayoutPanel11.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel11.Controls.Add(this.label2, 0, 1);
            this.tableLayoutPanel11.Controls.Add(this.textBox1, 1, 0);
            this.tableLayoutPanel11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel11.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel11.Name = "tableLayoutPanel11";
            this.tableLayoutPanel11.RowCount = 8;
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel11.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel11.Size = new System.Drawing.Size(286, 629);
            this.tableLayoutPanel11.TabIndex = 0;
            // 
            // textBox7
            // 
            this.textBox7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox7.Location = new System.Drawing.Point(179, 276);
            this.textBox7.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox7.Name = "textBox7";
            this.textBox7.ReadOnly = true;
            this.textBox7.Size = new System.Drawing.Size(104, 20);
            this.textBox7.TabIndex = 17;
            // 
            // textBox6
            // 
            this.textBox6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox6.Location = new System.Drawing.Point(179, 232);
            this.textBox6.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox6.Name = "textBox6";
            this.textBox6.ReadOnly = true;
            this.textBox6.Size = new System.Drawing.Size(104, 20);
            this.textBox6.TabIndex = 16;
            // 
            // textBox5
            // 
            this.textBox5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox5.Location = new System.Drawing.Point(179, 188);
            this.textBox5.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox5.Name = "textBox5";
            this.textBox5.ReadOnly = true;
            this.textBox5.Size = new System.Drawing.Size(104, 20);
            this.textBox5.TabIndex = 15;
            // 
            // textBox3
            // 
            this.textBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox3.Location = new System.Drawing.Point(179, 144);
            this.textBox3.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox3.Name = "textBox3";
            this.textBox3.ReadOnly = true;
            this.textBox3.Size = new System.Drawing.Size(104, 20);
            this.textBox3.TabIndex = 14;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label10.Location = new System.Drawing.Point(3, 264);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(170, 44);
            this.label10.TabIndex = 13;
            this.label10.Text = "Minutes per Level";
            this.label10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label8.Location = new System.Drawing.Point(3, 220);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(170, 44);
            this.label8.TabIndex = 11;
            this.label8.Text = "Milisecond per Level";
            this.label8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label6.Location = new System.Drawing.Point(3, 176);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(170, 44);
            this.label6.TabIndex = 9;
            this.label6.Text = "Time per Treatment";
            this.label6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label6.Click += new System.EventHandler(this.label6_Click);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label4.Location = new System.Drawing.Point(3, 132);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(170, 44);
            this.label4.TabIndex = 7;
            this.label4.Text = "Treatment Per Patient";
            this.label4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label3.Location = new System.Drawing.Point(3, 88);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(170, 44);
            this.label3.TabIndex = 6;
            this.label3.Text = "Number of Patients";
            this.label3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // textBox4
            // 
            this.textBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox4.Location = new System.Drawing.Point(179, 100);
            this.textBox4.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox4.Name = "textBox4";
            this.textBox4.ReadOnly = true;
            this.textBox4.Size = new System.Drawing.Size(104, 20);
            this.textBox4.TabIndex = 5;
            // 
            // textBox2
            // 
            this.textBox2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox2.Location = new System.Drawing.Point(179, 56);
            this.textBox2.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox2.Name = "textBox2";
            this.textBox2.ReadOnly = true;
            this.textBox2.Size = new System.Drawing.Size(104, 20);
            this.textBox2.TabIndex = 3;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label1.Location = new System.Drawing.Point(3, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(170, 44);
            this.label1.TabIndex = 0;
            this.label1.Text = "Average Entry Time Per Patient";
            this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label2.Location = new System.Drawing.Point(3, 44);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(170, 44);
            this.label2.TabIndex = 1;
            this.label2.Text = "Time Between Patients";
            this.label2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // textBox1
            // 
            this.textBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox1.Location = new System.Drawing.Point(179, 12);
            this.textBox1.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new System.Drawing.Size(104, 20);
            this.textBox1.TabIndex = 2;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.balancingRoomList);
            this.groupBox3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox3.Location = new System.Drawing.Point(3, 3);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(144, 648);
            this.groupBox3.TabIndex = 0;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Room List";
            // 
            // balancingRoomList
            // 
            this.balancingRoomList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.balancingRoomList.FormattingEnabled = true;
            this.balancingRoomList.Location = new System.Drawing.Point(3, 16);
            this.balancingRoomList.Name = "balancingRoomList";
            this.balancingRoomList.Size = new System.Drawing.Size(138, 629);
            this.balancingRoomList.TabIndex = 0;
            this.balancingRoomList.Click += new System.EventHandler(this.onBalancingCategorySelected);
            // 
            // groupBox4
            // 
            this.groupBox4.Controls.Add(this.tableLayoutPanel10);
            this.groupBox4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox4.Location = new System.Drawing.Point(153, 3);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new System.Drawing.Size(244, 648);
            this.groupBox4.TabIndex = 1;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Difficulty Modifier";
            // 
            // tableLayoutPanel10
            // 
            this.tableLayoutPanel10.ColumnCount = 1;
            this.tableLayoutPanel10.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel10.Controls.Add(this.difficultyModifierList, 0, 0);
            this.tableLayoutPanel10.Controls.Add(this.tableLayoutPanel13, 0, 1);
            this.tableLayoutPanel10.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel10.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel10.Name = "tableLayoutPanel10";
            this.tableLayoutPanel10.RowCount = 2;
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel10.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel10.Size = new System.Drawing.Size(238, 629);
            this.tableLayoutPanel10.TabIndex = 0;
            // 
            // difficultyModifierList
            // 
            this.difficultyModifierList.Dock = System.Windows.Forms.DockStyle.Fill;
            this.difficultyModifierList.FormattingEnabled = true;
            this.difficultyModifierList.Location = new System.Drawing.Point(3, 3);
            this.difficultyModifierList.Name = "difficultyModifierList";
            this.difficultyModifierList.SelectionMode = System.Windows.Forms.SelectionMode.MultiSimple;
            this.difficultyModifierList.Size = new System.Drawing.Size(232, 583);
            this.difficultyModifierList.TabIndex = 0;
            // 
            // tableLayoutPanel13
            // 
            this.tableLayoutPanel13.ColumnCount = 3;
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel13.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel13.Controls.Add(this.buttonAddDiffModifier, 0, 0);
            this.tableLayoutPanel13.Controls.Add(this.buttonRemoveDiffModifier, 1, 0);
            this.tableLayoutPanel13.Controls.Add(this.diffModifierValue, 2, 0);
            this.tableLayoutPanel13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel13.Location = new System.Drawing.Point(3, 592);
            this.tableLayoutPanel13.Name = "tableLayoutPanel13";
            this.tableLayoutPanel13.RowCount = 1;
            this.tableLayoutPanel13.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel13.Size = new System.Drawing.Size(232, 34);
            this.tableLayoutPanel13.TabIndex = 1;
            // 
            // buttonAddDiffModifier
            // 
            this.buttonAddDiffModifier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonAddDiffModifier.Location = new System.Drawing.Point(3, 3);
            this.buttonAddDiffModifier.Name = "buttonAddDiffModifier";
            this.buttonAddDiffModifier.Size = new System.Drawing.Size(71, 28);
            this.buttonAddDiffModifier.TabIndex = 0;
            this.buttonAddDiffModifier.Text = "Add";
            this.buttonAddDiffModifier.UseVisualStyleBackColor = true;
            this.buttonAddDiffModifier.Click += new System.EventHandler(this.buttonAddDiffModifier_Click);
            // 
            // buttonRemoveDiffModifier
            // 
            this.buttonRemoveDiffModifier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.buttonRemoveDiffModifier.Location = new System.Drawing.Point(80, 3);
            this.buttonRemoveDiffModifier.Name = "buttonRemoveDiffModifier";
            this.buttonRemoveDiffModifier.Size = new System.Drawing.Size(71, 28);
            this.buttonRemoveDiffModifier.TabIndex = 1;
            this.buttonRemoveDiffModifier.Text = "Remove";
            this.buttonRemoveDiffModifier.UseVisualStyleBackColor = true;
            this.buttonRemoveDiffModifier.Click += new System.EventHandler(this.buttonRemoveDiffModifier_Click);
            // 
            // diffModifierValue
            // 
            this.diffModifierValue.DecimalPlaces = 1;
            this.diffModifierValue.Dock = System.Windows.Forms.DockStyle.Fill;
            this.diffModifierValue.Increment = new decimal(new int[] {
            5,
            0,
            0,
            65536});
            this.diffModifierValue.Location = new System.Drawing.Point(157, 3);
            this.diffModifierValue.Name = "diffModifierValue";
            this.diffModifierValue.Size = new System.Drawing.Size(72, 20);
            this.diffModifierValue.TabIndex = 2;
            // 
            // groupBox5
            // 
            this.groupBox5.Controls.Add(this.tableLayoutPanel12);
            this.groupBox5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.groupBox5.Location = new System.Drawing.Point(701, 3);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new System.Drawing.Size(285, 648);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Global Values";
            // 
            // tableLayoutPanel12
            // 
            this.tableLayoutPanel12.ColumnCount = 2;
            this.tableLayoutPanel12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61.76471F));
            this.tableLayoutPanel12.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 38.23529F));
            this.tableLayoutPanel12.Controls.Add(this.textBox8, 1, 6);
            this.tableLayoutPanel12.Controls.Add(this.textBox9, 1, 5);
            this.tableLayoutPanel12.Controls.Add(this.textBox10, 1, 4);
            this.tableLayoutPanel12.Controls.Add(this.textBox11, 1, 3);
            this.tableLayoutPanel12.Controls.Add(this.label5, 0, 6);
            this.tableLayoutPanel12.Controls.Add(this.label7, 0, 5);
            this.tableLayoutPanel12.Controls.Add(this.label9, 0, 4);
            this.tableLayoutPanel12.Controls.Add(this.label11, 0, 3);
            this.tableLayoutPanel12.Controls.Add(this.label12, 0, 2);
            this.tableLayoutPanel12.Controls.Add(this.textBox12, 1, 2);
            this.tableLayoutPanel12.Controls.Add(this.textBox13, 1, 1);
            this.tableLayoutPanel12.Controls.Add(this.label13, 0, 0);
            this.tableLayoutPanel12.Controls.Add(this.label14, 0, 1);
            this.tableLayoutPanel12.Controls.Add(this.textBox14, 1, 0);
            this.tableLayoutPanel12.Controls.Add(this.textBox19, 1, 8);
            this.tableLayoutPanel12.Controls.Add(this.textBox20, 1, 9);
            this.tableLayoutPanel12.Controls.Add(this.label15, 0, 8);
            this.tableLayoutPanel12.Controls.Add(this.label16, 0, 9);
            this.tableLayoutPanel12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel12.Location = new System.Drawing.Point(3, 16);
            this.tableLayoutPanel12.Name = "tableLayoutPanel12";
            this.tableLayoutPanel12.RowCount = 11;
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle());
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel12.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel12.Size = new System.Drawing.Size(279, 629);
            this.tableLayoutPanel12.TabIndex = 1;
            this.tableLayoutPanel12.Paint += new System.Windows.Forms.PaintEventHandler(this.tableLayoutPanel12_Paint);
            // 
            // textBox8
            // 
            this.textBox8.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox8.Location = new System.Drawing.Point(175, 276);
            this.textBox8.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox8.Name = "textBox8";
            this.textBox8.ReadOnly = true;
            this.textBox8.Size = new System.Drawing.Size(101, 20);
            this.textBox8.TabIndex = 17;
            // 
            // textBox9
            // 
            this.textBox9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox9.Location = new System.Drawing.Point(175, 232);
            this.textBox9.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox9.Name = "textBox9";
            this.textBox9.ReadOnly = true;
            this.textBox9.Size = new System.Drawing.Size(101, 20);
            this.textBox9.TabIndex = 16;
            // 
            // textBox10
            // 
            this.textBox10.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox10.Location = new System.Drawing.Point(175, 188);
            this.textBox10.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox10.Name = "textBox10";
            this.textBox10.ReadOnly = true;
            this.textBox10.Size = new System.Drawing.Size(101, 20);
            this.textBox10.TabIndex = 15;
            // 
            // textBox11
            // 
            this.textBox11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox11.Location = new System.Drawing.Point(175, 144);
            this.textBox11.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox11.Name = "textBox11";
            this.textBox11.ReadOnly = true;
            this.textBox11.Size = new System.Drawing.Size(101, 20);
            this.textBox11.TabIndex = 14;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label5.Location = new System.Drawing.Point(3, 264);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(166, 44);
            this.label5.TabIndex = 13;
            this.label5.Text = "DecreaseTimePerTreatment";
            this.label5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label7.Location = new System.Drawing.Point(3, 220);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(166, 44);
            this.label7.TabIndex = 11;
            this.label7.Text = "InitialTimePerTreatment";
            this.label7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label9.Location = new System.Drawing.Point(3, 176);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(166, 44);
            this.label9.TabIndex = 9;
            this.label9.Text = "DecreaseTimeBetweenPatients";
            this.label9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label11
            // 
            this.label11.AutoSize = true;
            this.label11.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label11.Location = new System.Drawing.Point(3, 132);
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(166, 44);
            this.label11.TabIndex = 7;
            this.label11.Text = "InitialTimeBetweenPatients";
            this.label11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label12.Location = new System.Drawing.Point(3, 88);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(166, 44);
            this.label12.TabIndex = 6;
            this.label12.Text = "TimeIncreasePerLevel";
            this.label12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // textBox12
            // 
            this.textBox12.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox12.Location = new System.Drawing.Point(175, 100);
            this.textBox12.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox12.Name = "textBox12";
            this.textBox12.ReadOnly = true;
            this.textBox12.Size = new System.Drawing.Size(101, 20);
            this.textBox12.TabIndex = 5;
            // 
            // textBox13
            // 
            this.textBox13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox13.Location = new System.Drawing.Point(175, 56);
            this.textBox13.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox13.Name = "textBox13";
            this.textBox13.ReadOnly = true;
            this.textBox13.Size = new System.Drawing.Size(101, 20);
            this.textBox13.TabIndex = 3;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label13.Location = new System.Drawing.Point(3, 0);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(166, 44);
            this.label13.TabIndex = 0;
            this.label13.Text = "DifficultyModifier Treatments Based";
            this.label13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label13.Click += new System.EventHandler(this.label13_Click);
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label14.Location = new System.Drawing.Point(3, 44);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(166, 44);
            this.label14.TabIndex = 1;
            this.label14.Text = "StartLevelDuration";
            this.label14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // textBox14
            // 
            this.textBox14.Dock = System.Windows.Forms.DockStyle.Fill;
            this.textBox14.Location = new System.Drawing.Point(175, 12);
            this.textBox14.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox14.Name = "textBox14";
            this.textBox14.ReadOnly = true;
            this.textBox14.Size = new System.Drawing.Size(101, 20);
            this.textBox14.TabIndex = 2;
            // 
            // textBox19
            // 
            this.textBox19.Location = new System.Drawing.Point(175, 320);
            this.textBox19.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox19.Name = "textBox19";
            this.textBox19.ReadOnly = true;
            this.textBox19.Size = new System.Drawing.Size(100, 20);
            this.textBox19.TabIndex = 22;
            // 
            // textBox20
            // 
            this.textBox20.Location = new System.Drawing.Point(175, 364);
            this.textBox20.Margin = new System.Windows.Forms.Padding(3, 12, 3, 12);
            this.textBox20.Name = "textBox20";
            this.textBox20.ReadOnly = true;
            this.textBox20.Size = new System.Drawing.Size(100, 20);
            this.textBox20.TabIndex = 23;
            // 
            // label15
            // 
            this.label15.AutoSize = true;
            this.label15.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label15.Location = new System.Drawing.Point(3, 308);
            this.label15.Name = "label15";
            this.label15.Size = new System.Drawing.Size(166, 44);
            this.label15.TabIndex = 24;
            this.label15.Text = "CheckoutPerPatient";
            this.label15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Dock = System.Windows.Forms.DockStyle.Fill;
            this.label16.Location = new System.Drawing.Point(3, 352);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(166, 44);
            this.label16.TabIndex = 25;
            this.label16.Text = "TreatmentMinimumTime";
            this.label16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 1;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Controls.Add(this.flowLayoutPanel1, 0, 1);
            this.tableLayoutPanel4.Controls.Add(this.tabControl1, 0, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(2);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 2;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(1007, 730);
            this.tableLayoutPanel4.TabIndex = 1;
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.AutoSize = true;
            this.flowLayoutPanel1.Controls.Add(this.cancelButton);
            this.flowLayoutPanel1.Controls.Add(this.saveButton);
            this.flowLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flowLayoutPanel1.Location = new System.Drawing.Point(2, 692);
            this.flowLayoutPanel1.Margin = new System.Windows.Forms.Padding(2);
            this.flowLayoutPanel1.MaximumSize = new System.Drawing.Size(0, 41);
            this.flowLayoutPanel1.MinimumSize = new System.Drawing.Size(0, 32);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.flowLayoutPanel1.Size = new System.Drawing.Size(1003, 36);
            this.flowLayoutPanel1.TabIndex = 2;
            // 
            // cancelButton
            // 
            this.cancelButton.Location = new System.Drawing.Point(945, 4);
            this.cancelButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.cancelButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(56, 24);
            this.cancelButton.TabIndex = 1;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.cancelButton.Click += new System.EventHandler(this.canelButton_Click);
            // 
            // saveButton
            // 
            this.saveButton.Location = new System.Drawing.Point(885, 4);
            this.saveButton.Margin = new System.Windows.Forms.Padding(2, 4, 2, 4);
            this.saveButton.MinimumSize = new System.Drawing.Size(0, 24);
            this.saveButton.Name = "saveButton";
            this.saveButton.Size = new System.Drawing.Size(56, 24);
            this.saveButton.TabIndex = 0;
            this.saveButton.Text = "Save";
            this.saveButton.UseVisualStyleBackColor = true;
            this.saveButton.Click += new System.EventHandler(this.saveButton_Click);
            // 
            // windowSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1007, 730);
            this.Controls.Add(this.tableLayoutPanel4);
            this.Margin = new System.Windows.Forms.Padding(2);
            this.MinimumSize = new System.Drawing.Size(604, 495);
            this.Name = "windowSettings";
            this.Text = "Settings";
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.projectDirectoryLayout.ResumeLayout(false);
            this.projectDirectoryLayout.PerformLayout();
            this.tabPatientTypes.ResumeLayout(false);
            this.patientTypesLayout.ResumeLayout(false);
            this.patientTypeAutoGenerated.ResumeLayout(false);
            this.patientTypeAutoGenerated.PerformLayout();
            this.patientTypeRoomGroup.ResumeLayout(false);
            this.PatientTypeChoicesGroup.ResumeLayout(false);
            this.tableLayoutPanel6.ResumeLayout(false);
            this.patientTypeOtherChoicesGroup.ResumeLayout(false);
            this.tableLayoutPanel7.ResumeLayout(false);
            this.patientTypeMaleChoicesGroup.ResumeLayout(false);
            this.patientTypeFemaleChoicesGroup.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.treatmentRoomListGroup.ResumeLayout(false);
            this.tableLayoutPanel8.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.treatmentDataGridView)).EndInit();
            this.flowLayoutPanel2.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tableLayoutPanel9.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.tableLayoutPanel11.ResumeLayout(false);
            this.tableLayoutPanel11.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.tableLayoutPanel10.ResumeLayout(false);
            this.tableLayoutPanel13.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.diffModifierValue)).EndInit();
            this.groupBox5.ResumeLayout(false);
            this.tableLayoutPanel12.ResumeLayout(false);
            this.tableLayoutPanel12.PerformLayout();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Label projectDirectoryLabel;
        private System.Windows.Forms.FlowLayoutPanel projectDirectoryLayout;
        private System.Windows.Forms.TextBox projectDirectoryPathText;
        private System.Windows.Forms.Button projectDirectoryBrowseButton;
        private System.Windows.Forms.TabPage tabPatientTypes;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.TabPage tabPage3;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.TableLayoutPanel patientTypesLayout;
        private System.Windows.Forms.GroupBox patientTypeAutoGenerated;
        private System.Windows.Forms.GroupBox patientTypeRoomGroup;
        private System.Windows.Forms.GroupBox PatientTypeChoicesGroup;
        private System.Windows.Forms.ListBox patientTypeRoomList;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button saveButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.GroupBox patientTypeOtherChoicesGroup;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel7;
        private System.Windows.Forms.GroupBox patientTypeMaleChoicesGroup;
        private System.Windows.Forms.GroupBox patientTypeFemaleChoicesGroup;
        private System.Windows.Forms.TextBox patientTypeListAutoGeneratedText;
        private System.Windows.Forms.CheckedListBox patientTypeMaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeFemaleCheckList;
        private System.Windows.Forms.CheckedListBox patientTypeOtherCheckList;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.GroupBox treatmentRoomListGroup;
        private System.Windows.Forms.ListBox treatmentRoomList;
        private System.Windows.Forms.ColorDialog colorDialog1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel8;
        private System.Windows.Forms.DataGridView treatmentDataGridView;
        private System.Windows.Forms.DataGridViewCheckBoxColumn treatmentSelect;
        private System.Windows.Forms.DataGridViewTextBoxColumn treatmentType;
        private System.Windows.Forms.DataGridViewComboBoxColumn difficultyUnlocked;
        private System.Windows.Forms.DataGridViewTextBoxColumn heartsValue;
        private System.Windows.Forms.DataGridViewTextBoxColumn weight;
        private System.Windows.Forms.DataGridViewTextBoxColumn weightPercentage;
        private System.Windows.Forms.DataGridViewCheckBoxColumn gesture;
        private System.Windows.Forms.DataGridViewCheckBoxColumn alwaysLast;
        private System.Windows.Forms.DataGridViewButtonColumn color;
        private System.Windows.Forms.DataGridViewTextBoxColumn colorValue;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel9;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel11;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.TextBox textBox4;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.ListBox balancingRoomList;
        private System.Windows.Forms.GroupBox groupBox4;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel10;
        private System.Windows.Forms.ListBox difficultyModifierList;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox textBox7;
        private System.Windows.Forms.TextBox textBox6;
        private System.Windows.Forms.TextBox textBox5;
        private System.Windows.Forms.TextBox textBox3;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.GroupBox groupBox5;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel12;
        private System.Windows.Forms.TextBox textBox8;
        private System.Windows.Forms.TextBox textBox9;
        private System.Windows.Forms.TextBox textBox10;
        private System.Windows.Forms.TextBox textBox11;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox textBox12;
        private System.Windows.Forms.TextBox textBox13;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.TextBox textBox14;
        private System.Windows.Forms.TextBox textBox19;
        private System.Windows.Forms.TextBox textBox20;
        private System.Windows.Forms.Label label15;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel13;
        private System.Windows.Forms.Button buttonAddDiffModifier;
        private System.Windows.Forms.Button buttonRemoveDiffModifier;
        private System.Windows.Forms.NumericUpDown diffModifierValue;
    }
}